Feature/evap subl pdf
GEOS-ESM/GEOSgcm_GridComp pull request #1008
Opened 2024-09-26 18:32 UTC by CharlesKrop

GFDL_1M evap_subl_pdf loop port. Verified, fail at a few points due to known constant issue.

find_klcl port. Created to test QSat port. Verifies, but not integrated into the larger GFDL_1M port.

2024-09-26 20:17 UTC, FlorianDeconinck requested changes
Good push!

Let's reshape things

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
Move to `GFDL_1M` since it's well named

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +):
```suggestion
):
# TODO: Workaround for hybrid indexing
```

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +        # wait = True
Still true?

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +        # self._temporary = self.quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
Remove

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +        # self.get_last(Q, self._temporary, self._Q_top)
Remove

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +        # self.qsat(self._T_top, self._P_top)
No need for `QSat`?

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +        for i in range(0, P.view[:].shape[0]):
```suggestion
        # TODO: Workaround for hybrid indexing (mask)
        for i in range(0, P.view[:].shape[0]):
```

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +if __name__ == "__main__":
Remove below, this will be `Translate` tested when finished

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +class evap_subl_pdf:
Rename to `EvapSublPdf` or even better something that make sense

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        # Temporary implementation of hybrid_index_2dout.py, perhaps not working as
?

If true then `#TODO`

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        if LMELTFRZ is True:
```suggestion
        if LMELTFRZ:
```

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +class find_klcl:
```suggestion
class FindKLCL
```

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/misc_unused/find_klcl.py
> +import copy
Top of the file docstring talking about "lifted condensation level"

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M_constants.py
No empty file (even if I understand the idea)

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M_util.py
Break into a `process_library.py` when needed.
Break the main function into their own file with description of what they are (or ??? if you don't know and we will hunt people that do)

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/extratypes.py
Rename `field_types.py`

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/extratypes.py
> +# Global space
Not needed

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
Keep as-is, I will refactor

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/saturation/table.py
> +    print(_cached_estimated_saturation.keys())
Remove `print`s

2024-09-26 20:17 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/run_tests.sh
Revert all changes here.

2024-09-26 20:32 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/extratypes.py
> +# Global space
need to keep line 5... right?

2024-09-26 20:33 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/extratypes.py
not sure what this is referencing, I don't see `field_types.py`

2024-09-26 20:54 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        # Temporary implementation of hybrid_index_2dout.py, perhaps not working as
nope, was an old comment

2024-09-27 16:47 UTC, FlorianDeconinck requested changes

2024-09-27 16:47 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +from .evap_subl_pdf_core import evap, hystpdf, initial_calc, meltfrz, subl
```suggestion
from .evap_subl_pdf_core import evap, hystpdf, initial_calc, meltfrz, subl
from pyMoist.GFDL_1M.evap_subl_pdf_core import evap, hystpdf, initial_calc, meltfrz, subl
```

Never relative imports.

2024-09-27 16:47 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/field_types.py
> +FloatField_Extra_Dim = gtscript.Field[gtscript.K, (Float, (int(TABLESIZE)))]
Let's rename this. This `FloatField_VaporSaturationTable`

2024-09-27 16:47 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_incloud_processes.py
> +"""Stencils and functions called by multiple pyMoist modules.
:+1:

2024-09-27 16:47 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_fundamental_math.py
:+1:

2024-09-27 16:47 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_data_manipulation.py
Rename `gt4py_workarounds`

2024-09-27 17:15 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +from .evap_subl_pdf_core import evap, hystpdf, initial_calc, meltfrz, subl
Remove this line

2024-09-27 17:55 UTC, FlorianDeconinck approved these changes

2024-10-04 16:50 UTC, twicki reviewed
I think there are a few open points to discuss still

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +class FindKLCL:
can we have a class docstring here?

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +        formulation: SaturationFormulation = SaturationFormulation.Staars,
this is unused

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +        use_table_lookup: bool = True,
this is unused

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +        self.qsat = QSat(
I don't like the declaration outside the init. Why is it here?

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/field_types.py
> +FloatField_VaporSaturationTable = gtscript.Field[gtscript.K, (Float, (int(TABLESIZE)))]
do we use this for anything that is not the VaporSaturationTable? If so can we rename it? 
```suggestion
VaporSaturationTable = gtscript.Field[gtscript.K, (Float, (int(TABLESIZE)))]
```

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +# File containing all constants used for pyMoist
This is not a properly formatted module docstring

2024-10-04 16:50 UTC, twicki commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +# Universal Constants
if we are groping them here, should we not group them into dataclasses?

2024-10-07 15:50 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        EIS: FloatFieldIJ,
Input from Fortran, leaving as is

2024-10-07 15:50 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        TURNRHCRIT_PARAM: Float,
Input from Fortran, leaving as is

2024-10-07 15:54 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        PDFSHAPE: Float,
Input from Fortran, leaving as is

2024-10-07 15:55 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        USE_BERGERON: bool = True,
Input from Fortran, leaving as is

2024-10-07 15:55 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +from ndsl import QuantityFactory, StencilFactory, orchestrate
Added

2024-10-07 16:02 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        self._PLEmb_top = self.quantity_factory.zeros([X_DIM, Y_DIM, Z_DIM], "n/a")
all of this top level stuff will be reworked once the k-level feature is integrated into ndsl. for now, I am going to leave it as is, I plan to get rid of most of these temporary quantities and the gt4py workaround functions in the near future.

2024-10-07 16:03 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        self._PLmb_at_klcl = self.quantity_factory.zeros([X_DIM, Y_DIM], "n/a")
see above comment

2024-10-07 16:03 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_gt4py_workarounds.py
> +def get_last(
see above comment

2024-10-07 16:05 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_gt4py_workarounds.py
> +    with computation(PARALLEL), interval(...):
this was done because I needed out_field to be a 3d version of a 2d field. I anticipate I will also be able to remove this once I call specific k-levels

2024-10-07 16:05 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_gt4py_workarounds.py
> +    """Workaround for absolute index in K and relative in I/J,
this will be deleted, so not touching them for now

2024-10-07 16:06 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        if LMELTFRZ is not True:
added a check_flags function that has all the error handling in it

2024-10-07 16:11 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/GFDL_1M.py
> +        self._meltfrz = self.stencil_factory.from_dims_halo(
renamed functions where possible (I am not 100% sure if hystpdf is supposed to mean "hydrostatic pdf" so I don't want to rename it that.

2024-10-07 16:39 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_gt4py_workarounds.py
> +    with computation(FORWARD), interval(-1, None):
will be removed once k level stuff is integrated into ndsl

2024-10-07 17:41 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/evap_subl_pdf_core.py
> +        elif qstar <= qtmin:
Yes, this is how the fortran is structured. presumably there is a case in which something can pass through unmodified... although to be honest this entire function appears unfinished. the (sparce) documentation suggests that there should be options for flag=1 2 and 3 but only flag=1 and 2 are present. Only flag = 1 is actually tested (flag = PDFSHAPE). I am going to restructure this, removing untested code and adding a comment that another option is present in fortran

2024-10-07 17:41 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/evap_subl_pdf_core.py
> +        elif qstar <= qtmin:
see above comment

2024-10-07 17:49 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/evap_subl_pdf_core.py
> +    # Completelely glaciated cloud:
I'm a little unsure what you are referencing here. Are you saying I should put everything below the comment at 149 into its own function? that code is never reused elsewhere in the model, so I don't see the value of adding the function there. In my mind it just adds more clutter (another function to chase down, more inputs/outputs to track)

2024-10-07 17:54 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +"""This function identifies the index of the lifted
fair. this is going to be moved unto GFDL_1M.py once I have a proper home for it. this was created as a way of testing the qsat code, it is still unfinished and has not been tested within the proper model

2024-10-07 17:57 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +    # TODO: Workaround for hybrid indexing
as mentioned above, this is far from its final form (and currently unused). I will rework this when I integrate it into GFDL_1M, so I'm not going to mess with it for now

2024-10-07 17:58 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/GFDL_1M/find_klcl.py
> +    with computation(FORWARD), interval(-1, None):
No reason. I didn't know what I was doing at the time. they don't have to be and they won't be in the future

2024-10-07 17:59 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_fundamental_math.py
> +    Calculate air density [kg/m^3]
I'll let Florian know you like it :)

2024-10-07 18:03 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/shared_fundamental_math.py
yes, my thought was that this is only basic mathematical calculations. I had originally called gt4py workarounds "data_manipulation" because I expected it to expand with time, but Florian wanted me to rename it to gt4py workaround because it is more appropriate for what it is now. To be honest, I expecte these shared scripts to change a little in the future as I get my hands on more code. I'm sure I'll have to subdivide further to avoid 5000 line Process_Library equivalents

2024-10-09 18:55 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +# Universal Constants
This makes sense, but considering I am going to wait until we have a proper solution to the constants issue and then restructure this entire system. I will add classes when I do that

2024-10-09 18:57 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +debug = True
Temporary workaround to fix the constant issue. Not 100%, but it is an improvement.

2024-10-09 19:37 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +rad_to_deg = 180 / PI
have not moved away from fortran naming yet, will get fixed in the final GFDL_1M clean up

2024-10-09 19:39 UTC, CharlesKrop commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/field_types.py
> +FloatField_VaporSaturationTable = gtscript.Field[gtscript.K, (Float, (int(TABLESIZE)))]
It seems like these sorts of things are going to be fairly common, so I am going to make a module that allows us to create these dynamically, at which point this entire file will be deleted

2024-10-11 15:02 UTC, FlorianDeconinck approved these changes
Two small edits and we can merge

2024-10-11 15:02 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/run_tests.sh
Revert this file

2024-10-11 15:15 UTC, merged