Updates to allow GEOS to build without MKL
GEOS-ESM/GEOSgcm_GridComp pull request #321
Opened 2020-07-28 16:56 UTC by mathomp4

This set of PRs is to allow GEOS to build without MKL. Note that it currently does this by making RRTMGP unusable if MKL is not found. This is not ideal, but it's a first attempt.

2020-09-04 12:57 UTC, tclune requested changes
Please add `find_package(MKL)` in CMakeLists.txt files for layers that need MKL.   This won't help much in the short term, but eventually will help disentangle dependencies for things like MAPL.

2020-09-04 17:48 UTC, tclune approved these changes

2020-09-22 12:47 UTC, tclune approved these changes
It is unfortunate that the CMake kludge for MKL Fortran is propagating - esp. since the right place to handle this should be inside the MKL package.

The loop (lines 3495-3510) wrapped by `#ifdef` seems suspicious.    Ideally we just have a different RNG and use it the same way as with MKL. ?

2020-09-22 12:57 UTC, mathomp4 commented
@tclune Yeah. I'm not saying this is the *best* fix, just a workaround. If you, me, or @dr0cloud could come up with an alternative RNG with the same interface, that might be best of all. Plus, it can make @dr0cloud 's life easier with merges with the parent RRTMGP repo if we can limit the ifdefs.

2020-09-22 13:04 UTC, sdrabenh approved these changes

2020-09-22 13:04 UTC, merged