dso for  mom5 and mom6
GEOS-ESM/GEOSgcm_GridComp pull request #377
Opened 2020-11-09 20:55 UTC by weiyuan-jiang

If this is working,  we can move on to the other components.
Timer is not working so far. I guess we need a libMAPL.so lib.
@mathomp4 @tclune

2020-11-09 21:47 UTC, tclune commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +  !use MOM6_GEOSPlugMod, only: MOM6SetServices => SetServices  ! this sets IRF
Before we approve the PR, I think these comments should be removed.  Otherwise they'll stay there forever.

2020-11-09 21:50 UTC, tclune commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM_GEOS5PlugMod.so',  __RC__)
The library name needs to come from a config file, not hardwired in the source.   This is very important in the long term.   But if you want to test that this all runs as is, it is fine for now.

I also think that MAPL_AddChild should add the "lib" prefix an the ".so" suffix (and .dylib suffix if using OS X as per the Teams discussion)

2020-11-09 21:51 UTC, tclune commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM6_GEOSPlug.so',  __RC__)
Probably not possible just yet, but we should next consult @yvikhlya and @sanAkel to see if the SELECT CASE here can be eliminated.   The library name (from the config file) should handle this aspect.

The reason this may not work is if the coupling is different for each ocean.  But if the connectivities are the same then this would be best.

2020-11-09 21:53 UTC, tclune requested changes
Some minor changes and a couple of questions.

2020-11-09 21:57 UTC, yvikhlya commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM6_GEOSPlug.so',  __RC__)
> Probably not possible just yet, but we should next consult @yvikhlya and @sanAkel to see if the SELECT CASE here can be eliminated. The library name (from the config file) should handle this aspect.
> 
> The reason this may not work is if the coupling is different for each ocean. But if the connectivities are the same then this would be best.

Connectivities for MOM5/MOM6 are not exactly the same.

2020-11-09 21:57 UTC, yvikhlya commented
Can I ask to provide a little more details on what are we trying to achieve here?

2020-11-09 22:02 UTC, tclune commented
@yvikhlya Sorry - everyone else had a discussion about this with me at one point or another.

The immediate driver is that the LD_PRELOAD "trick" is not working with MPT.   But using DSO's that are specified at run time was always the long term plan.   We just did not have a priority until now.    We think that this will be more robust and portable, and ultimately much more flexible.     A related set of changes (months away at best) will be to make the connectivities come from resource files as well instead of expressing them as hard coded logic in the component.   Then you would simply use a different `.rc` file for MOM5 runs than the one you would use for MOM6 runs.

Happy to discuss in person later this week if you would like.

2020-11-09 22:04 UTC, tclune commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM6_GEOSPlug.so',  __RC__)
OK - then the separate logic needs to remain for now.

2020-11-10 03:27 UTC, weiyuan-jiang commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM_GEOS5PlugMod.so',  __RC__)
As long as we can get those from a config file, the prefix and suffix are not important any more.  We can standardize the label  without "lib" and ".so" ( or ".dylib")

2020-11-10 13:11 UTC, tclune commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90
> +             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj='libMOM_GEOS5PlugMod.so',  __RC__)
OK - I'll mark as resolved then, in anticipation of the change.     I suspect we should get the coupled ocean people to test with the system as-is before we do additional polishing of the implementation.    I don't really expect any issues, but best to be sure.

2020-11-10 17:02 UTC, sanAkel commented
Hello All! @weiyuan-jiang @tclune @mathomp4 
I can try and test it.

For that, a question! 
Do we still need this in `gcm_run.j`: `@OCEAN_PRELOAD $RUN_CMD` $NPES ./GEOSgcm.x
https://github.com/GEOS-ESM/GEOSgcm_App/blob/6f973281f2b578016b7a38b8efa619cb6c833e12/gcm_run.j#L786

2020-11-10 19:51 UTC, tclune commented
No - with this approach the PRELOAD step is not needed and should be skipped.  But we are still waiting for some related changes to be made in baselibs.   So no testing yet.

2020-11-10 20:52 UTC, weiyuan-jiang commented
I would like your help to test it.  I failed ( I don't know how to run MOM) but I want to make sure that it is indeed the code's problem. @sanAkel

2020-11-10 21:36 UTC, sanAkel commented
> I would like your help to test it. I failed ( I don't know how to run MOM) but I want to make sure that it is indeed the code's problem. @sanAkel

@weiyuan-jiang I was under the impression from @tclune that we need a change in baselibs that @tclune and @mathomp4 are coordinating. Without those changes, this cannot be tested. @tclune , did I misunderstand?

2020-11-10 22:11 UTC, tclune commented
@sanAkel you did not misunderstand _me_.  But I may have misunderstood others.  Or we're just talking about who does what when we finally can.

2020-11-10 22:37 UTC, sanAkel requested changes

2020-11-10 22:37 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/CMakeLists.txt
> +#set (rename_MOM_GEOS5PlugMod MOM_GEOS5Plug)
Please remove commented lines. 

If we don't need something, please take it off!

2020-11-10 22:37 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
> +subroutine SetServices(gc, rc)
This `subroutine SetServices` is confusing! There is one already, just above `Initialize` Also where is the _body_ of `mySetServices`? Is this some MAPL _magic_?

2020-11-10 22:37 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90
> +   use MOM_GEOS5PlugMod, only : mySetservices=>SetServices
Same comment/questions as for the `MOM6_GEOSPlug.F90`

2020-11-12 01:49 UTC, sanAkel reviewed
@weiyuan-jiang Thank you making these changes. 
- I do like the `../GuestOcean_GridComp/CMakeLists.txt` It is simple and does exactly what it says! Very nice! 😄 

However, I was expecting to see some explanation behind the logic for this SetServices that has been introduced, in both MOM5 and MOM6 plugs, e.g., MOM5_Plug: https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/002a899f6758b463555634dbac69b9709f6db52d/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM_GEOS5PlugMod/MOM_GEOS5PlugMod.F90#L2150-L2156 

I don't get it! 
1. why is outside the module (MOM_GEOS5PlugMod) 
2. what is its utility?

Thanks!

2020-11-12 04:10 UTC, weiyuan-jiang commented
@sanAkel , If you check the CMakeLists.txt under GuestOcean_GridComp, you would see it does not depend on MOM5 or MOM6 during compiling.  GuestOcean_GridComp, MOM5 and MOM6 can be built independently.  However, GuesOcean_GridComp does need to call the SetServices subroutines in MOM6 or MOM5 during run time.  If the SetServices subroutuine is inside the module,  they can not be found through compatible name mangling, i.e., different compilers may generate different names, or the bind (c) would not work for some compilers. So we add a subroutine outside the module and the parent gridcomp can find it through "standard" name "setservices_" .    please see this https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/002a899f6758b463555634dbac69b9709f6db52d/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/GuestOcean_GridComp.F90#L120-L124

2020-11-13 19:59 UTC, weiyuan-jiang commented
Hi, All, I have tested GEOSgcm feature/wjiang/mom_dso branch which uses some other branches ( including this branch of GEOSgcm_GridComp). Basically, it needs these shared libraries :  

libfms_r4.so  libfms_r8.so  libMAPL.profiler.so  libMAPL.so  libMOM6_GEOSPlug.so  libmom6.so  libMOM_GEOS5PlugMod.so  libmom.so .

@sanAkel , If you want to test it, you can run gcm as usual without preloading, i.e.
   
   $RUN_CMD $NPES ./GEOSgcm.x $IOSERVER_OPTIONS --logging_config 'logging.yaml'

There may be a problem to build partial shared libraries though. It seems to me the compiling crashes more often. You need to make install again when it failed. I don't know why, maybe I was just unlucky.

2020-11-24 18:24 UTC, sanAkel commented
@sdrabenh We have not tested this. Please do not merge unless we do so. Thanks!

2020-11-25 17:04 UTC, sanAkel commented
Testing should include **coupled** model runs. 

- Logs are at: <...> **please fill in**

- **debug** build, not checking for zero-diff. (When debugging, zero-diff is _not needed_.) Run for 1 hour, with 450 s time step. 
    - [ ] MOM5 runs 
    - [ ] MOM6 runs

- **optim** build, Run for **6 hours**, with 450 s time step. Testing zero-diff to `develop` <**date**>  and <**SHA**>
    -  MOM5: 
       +  [ ] runs
       +  [ ] zero-diff
       
    - MOM6:
       +  [ ] runs
       +  [ ] zero-diff

2020-11-27 20:50 UTC, yvikhlya commented
I got an error while compiling this:
```
/gpfsm/dnb02/projects/p23/yvikhlia/coupled/GEOSgcm_main/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/Guest
Ocean_GridComp/GuestOcean_GridComp.F90(121): error #6284: There is no matching specific function for this generic function referenc
e.   [MAPL_ADDCHILD]
             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj=sharedObj,  RC=STATUS); if(MAPL_Verify(STATUS,"G
uestOcean_GridComp.F90",121 ,rc)) return
-------------------^
/gpfsm/dnb02/projects/p23/yvikhlia/coupled/GEOSgcm_main/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/Guest
Ocean_GridComp/GuestOcean_GridComp.F90(124): error #6284: There is no matching specific function for this generic function referenc
e.   [MAPL_ADDCHILD]
             OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj=sharedObj,  RC=STATUS); if(MAPL_Verify(STATUS,"G
uestOcean_GridComp.F90",124 ,rc)) return
```

2020-11-27 20:54 UTC, sanAkel commented
> I got an error while compiling this:
> 
> ```
> 
> /gpfsm/dnb02/projects/p23/yvikhlia/coupled/GEOSgcm_main/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/Guest
> 
> Ocean_GridComp/GuestOcean_GridComp.F90(121): error #6284: There is no matching specific function for this generic function referenc
> 
> e.   [MAPL_ADDCHILD]
> 
>              OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj=sharedObj,  RC=STATUS); if(MAPL_Verify(STATUS,"G
> 
> uestOcean_GridComp.F90",121 ,rc)) return
> 
> -------------------^
> 
> /gpfsm/dnb02/projects/p23/yvikhlia/coupled/GEOSgcm_main/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/Guest
> 
> Ocean_GridComp/GuestOcean_GridComp.F90(124): error #6284: There is no matching specific function for this generic function referenc
> 
> e.   [MAPL_ADDCHILD]
> 
>              OCN = MAPL_AddChild(OCEAN_NAME,'setservices_', parentGC=GC, sharedObj=sharedObj,  RC=STATUS); if(MAPL_Verify(STATUS,"G
> 
> uestOcean_GridComp.F90",124 ,rc)) return
> 
> ```
> 
> 
> 
> Which version of MAPL should I use?

@yvikhlya as per one of  @weiyuan-jiang 's remark above, did you try to compile one more time?

2020-11-27 21:45 UTC, yvikhlya commented
> @yvikhlya as per one of @weiyuan-jiang 's remark above, did you try to compile one more time?

It consistently fails with same error.

2020-11-30 12:50 UTC, tclune commented
The message suggests that you do not have one of the latest versions of MAPL that provides the new interface for AddChild.  Can you check the version of MAPL you are using and post here?

2020-11-30 13:59 UTC, yvikhlya commented
> The message suggests that you do not have one of the latest versions of MAPL that provides the new interface for AddChild. Can you check the version of MAPL you are using and post here?

It is v2.4.0, the one from GEOSgcm main.

2020-11-30 15:38 UTC, tclune commented
@yvikhlya  sorry - I only realized just now that we had never merged Weiyuan's changes into MAPL develop.   You will need to use his feature branch for the moment:

```cmake
MAPL:
  local: ./src/Shared/@MAPL
  remote: ../MAPL.git
  branch: feature/wjiang/mom_dso
  develop: develop
```

2020-11-30 15:40 UTC, tclune commented
@weiyuan-jiang recommends 
"The best way for him to test is to check out my feature/wjiang/mom_dso in GEOSgcm . Not just in GEOSgcm_GridComp."

He is having issues connecting to GitHub this morning.

2020-11-30 17:34 UTC, yvikhlya commented
Ok, I got feature/wjiang/mom_dso in GEOSgcm. Now cmake complains about not being able to find netcdf.h

```
CMake Error at @cmake/@ecbuild/cmake/ecbuild_log.cmake:168 (message):
  ERROR - "netcdf.h" is not found for NetCDF component C
Call Stack (most recent call first):
  @cmake/@ecbuild/cmake/contrib/FindNetCDF4.cmake:200 (ecbuild_error)
  @cmake/@ecbuild/cmake/FindNetCDF.cmake:94 (find_package)
  src/Shared/@MAPL/CMakeLists.txt:51 (find_package)
```

My modules and BASEDIR
```
Currently Loaded Modules:
  1) git/2.24.0               4) other/mepo             7) other/git-lfs/2.11.0  10) comp/intel/19.1.2.254
  2) cmake/3.17.0             5) other/tig/2.5.0        8) GEOSenv               11) mpi/impi/19.1.2.254
  3) other/manage_externals   6) ImageMagick/7.0.9-16   9) comp/gcc/8.3.0        12) python/GEOSpyD/Min4.8.3_py2.7

$ echo $BASEDIR
/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254
```

2020-11-30 18:17 UTC, weiyuan-jiang commented
Can you show me your test directory? I have tested my run here : /gpfsm/dnb32/wjiang/test_mom_dso

2020-11-30 18:18 UTC, yvikhlya commented
> Can you show me your test directory? I have tested my run here : /gpfsm/dnb32/wjiang/test_mom_dso

I don't have a test directory. I can't even build the model.

2020-11-30 18:25 UTC, weiyuan-jiang commented
Where is the directory you tried to build?

2020-11-30 18:30 UTC, yvikhlya commented
> Where is the directory you tried to build?

/home/yvikhlia/aogcm/coupled/GEOSgcm_dso

2020-11-30 18:31 UTC, sanAkel commented
> > Where is the directory you tried to build?
> 
> /home/yvikhlia/aogcm/coupled/GEOSgcm_dso

@weiyuan-jiang , @yvikhlya please continue _this kind_ of conversation in MS Teams!

2020-11-30 18:51 UTC, weiyuan-jiang commented
@mathomp4 ,  Are these three components still working together? 
env                    | (t) v3.0.1 (DH)
cmake                  | (t) v3.2.1 (DH)
ecbuild                | (t) geos/v1.0.5 (DH)

Error:

-- HDF5: Using hdf5 compiler wrapper to determine C configuration
CMake Error at @cmake/@ecbuild/cmake/ecbuild_log.cmake:168 (message):
  ERROR - "netcdf.h" is not found for NetCDF component C
Call Stack (most recent call first):
  @cmake/@ecbuild/cmake/contrib/FindNetCDF4.cmake:200 (ecbuild_error)
  @cmake/@ecbuild/cmake/FindNetCDF.cmake:94 (find_package)
  src/Shared/@MAPL/CMakeLists.txt:51 (find_package)


CMake Error at @cmake/@ecbuild/cmake/ecbuild_log.cmake:168 (message):
  ERROR - "netcdf.h" is not found for NetCDF component FORTRAN

2020-11-30 19:19 UTC, tclune commented
This is probably my fault.   I had to resolve a conflict in Weiyuan's changes that stepped on some unrelated work in how we use ESMF and NetCDF in cmake.     You probably need to update to the latest ESMA_Cmake.     I am a bit confused though, as even MAPL main now has the approach I used in the merge.

2020-11-30 19:31 UTC, mathomp4 commented
> @mathomp4 , Are these three components still working together?
> env | (t) v3.0.1 (DH)
> cmake | (t) v3.2.1 (DH)
> ecbuild | (t) geos/v1.0.5 (DH)
> 

@weiyuan-jiang and @yvikhlya I think the issue is that the MAPL might be out-of-sync. MAPL 2.4 (and anything based off it like `develop` and your branch in MAPL) requires ESMA_cmake 3.3.

I think you might need to rebase your branch on the fixture. I can do this for you, if you like?

2020-11-30 19:34 UTC, mathomp4 commented
I just did a quick merge locally and found this as the difference when done:
```diff
diff --git a/components.yaml b/components.yaml
index 6b6d33e..0b6e81d 100644
--- a/components.yaml
+++ b/components.yaml
@@ -36,19 +36,19 @@ GMAO_Shared:
 MAPL:
   local: ./src/Shared/@MAPL
   remote: ../MAPL.git
-  tag: v2.4.0
+  branch: feature/wjiang/mom_dso
   develop: develop

 FMS:
   local: ./src/Shared/@FMS
   remote: ../FMS.git
-  tag: geos/2019.01.02+noaff.3
+  branch: feature/wjiang/mom_dso
   develop: geos/release/2019.01

 GEOSgcm_GridComp:
   local: ./src/Components/@GEOSgcm_GridComp
   remote: ../GEOSgcm_GridComp.git
-  tag: v1.11.3
+  branch: feature/wjiang/mom_dso
   sparse: ./config/GEOSgcm_GridComp.sparse
   develop: develop
```

2020-12-02 22:27 UTC, yvikhlya commented
This update runs with MOM5/MOM6 mode with optimized build. Debug build runs with MOM6 and crashes with MOM5 in FMS diagnostics manager in finalize (at the very end of 1 day run). I guess, MOM5 plug CMakeLists need to be updated to have less strict checks in debug mode.

2020-12-03 02:40 UTC, sanAkel commented
> This update runs with MOM5/MOM6 mode with optimized build. Debug build runs with MOM6 and crashes with MOM5 in FMS diagnostics manager in finalize (at the very end of 1 day run). I guess, MOM5 plug CMakeLists need to be updated to have less strict checks in debug mode.

MOM5 debug did not have any issue about a week ago https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382#issuecomment-733187697

@weiyuan-jiang , @tclune , how and why do modifications in _this_ PR would need MOM5 CMakeLists.txt to be revised for its debug build? Or is it all the _other_ changes (MAPL, ESMA_cmake, etc) that have interfered in some way?

In any case, if that is needed, @mathomp4 would you please help! Thanks!

2020-12-03 03:59 UTC, weiyuan-jiang commented
Without details about the crashing, I could not know what was wrong. But the branch of feature/wjiang/mom_dso at MAPL may have problems.    I have updated that branch to feature/wjiang/mapl_shared_lib  in MAPL.

2020-12-03 13:41 UTC, tclune commented
My sense is that if anything is running at all with the DSO changes, then the DSO support is most likely working correctly.  The exposure of previously unseen problems when activating debugging is usually caused by revealing a long standing bug related to memory corruption that exhibits new symptoms due to changes in the memory allocation pattern.    Not that this helps very much .

First step has to be to reproduce the debug failure and see what can be learned from the nature and location of the crash.   Hopefully this will quickly point at the underlying problem.   Otherwise, I fear we are back to the situation we had a few weeks ago where something in the MOM+FMS layer is "bad" (or the compiler) and we don't know where.

Failing that, it might be illuminating to try a debug run with GFortran.

2020-12-03 14:31 UTC, mathomp4 commented
> > This update runs with MOM5/MOM6 mode with optimized build. Debug build runs with MOM6 and crashes with MOM5 in FMS diagnostics manager in finalize (at the very end of 1 day run). I guess, MOM5 plug CMakeLists need to be updated to have less strict checks in debug mode.
> 
> MOM5 debug did not have any issue about a week ago [#382 (comment)](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382#issuecomment-733187697)
> 
> @weiyuan-jiang , @tclune , how and why do modifications in _this_ PR would need MOM5 CMakeLists.txt to be revised for its debug build? Or is it all the _other_ changes (MAPL, ESMA_cmake, etc) that have interfered in some way?
> 
> In any case, if that is needed, @mathomp4 would you please make the same change as for MOM6 CMakeLists.txt https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382/files#diff-99acbf9a2102509758cd629f1f6c010e975609cd667618e371c29475811604ab
> 🙇‍♂️

If you want to try this out, there is a branch on the mom5 repo:
```
feature/mathomp4/degrade-intel-debug-flags
```
which just adds this code there.

2020-12-03 17:20 UTC, sanAkel commented
> 
> If you want to try this out, there is a branch on the mom5 repo:
> 
> ```
> feature/mathomp4/degrade-intel-debug-flags
> ```
> 
> which just adds this code there.

@mathomp4 , Thank you!

@yvikhlya, please try _this_ update and that one https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377#issuecomment-737649991 from @weiyuan-jiang. 

Hopefully it will work out! 🤞

2020-12-03 20:11 UTC, yvikhlya commented
After update to `feature/mathomp4/degrade-intel-debug-flags` in MOM5 and `feature/wjiang/mapl_shared_lib` in MAPL, MOM5 run still crashes with debug build. Log file:
```
/gpfsm/dhome/yvikhlia/geos5/xxx_mom5/log.txt
```

2020-12-03 20:55 UTC, mathomp4 commented
> After update to `feature/mathomp4/degrade-intel-debug-flags` in MOM5 and `feature/wjiang/mapl_shared_lib` in MAPL, MOM5 run still crashes with debug build. Log file:
> 
> ```
> /gpfsm/dhome/yvikhlia/geos5/xxx_mom5/log.txt
> ```

Does your FMS CMakeLists.txt also have the "degrade intel flags" chunk like the "stock" one does?

2020-12-03 20:57 UTC, yvikhlya commented
> > After update to `feature/mathomp4/degrade-intel-debug-flags` in MOM5 and `feature/wjiang/mapl_shared_lib` in MAPL, MOM5 run still crashes with debug build. Log file:
> > ```
> > /gpfsm/dhome/yvikhlia/geos5/xxx_mom5/log.txt
> > ```
> 
> Does your FMS CMakeLists.txt also have the "degrade intel flags" chunk like the "stock" one does?

No, it did not. I copied them from MOM5 CMakeLists, testing again.

2020-12-03 21:27 UTC, yvikhlya commented
All right, degrading intel flags in FMS fixed MOM5 crash with debug build.

Now, what about these zero-diff test? Should `feature/wjiang/mom_dso` indeed be zero diff with develop head?

2020-12-03 21:48 UTC, sanAkel commented
> All right, degrading intel flags in FMS fixed MOM5 crash with debug build.
> 
> Now, what about these zero-diff test? Should `feature/wjiang/mom_dso` indeed be zero diff with develop head?

@yvikhlya I think it should be zero-diff for both MOM5 and MOM6 in optimized build. We don't care about for zero-diff in debug build!

2020-12-03 22:03 UTC, sanAkel commented
@weiyuan-jiang I am chatting with @yvikhlya 

- [ ] Were you ever able to **run**?
- [ ] Is it `zero` diff?  I just took label off because this seems not the case!


With all these changes, to me it sounds like this entire PR needs to be rebased (or _something_??) with develop so we can do zero-diff tests ourselves before it gets to @sdrabenh

2020-12-05 04:19 UTC, sanAkel commented
> I have run mom6 but didn't do the comparison. The change is suppose to be zero-diff ( but...) . This PR would not work without support from MAPL 

@weiyuan-jiang in that case, would yourself or @tclune or @mathomp4 please confirm if the _develop_ version of MAPL  supports it or not. 

If not yet, we can wait!

Please just let us know when all is ready. Thanks!

2020-12-07 13:49 UTC, tclune commented
@sanAkel Sorry - there is a slight delay.  The MAPL changes are themselves ok, but they fail the CI tests because of necessary changes in upstream.  (We test MAPL by building the GCM).    Should be soon.

2020-12-08 19:57 UTC, mathomp4 commented
> Sorry - there is a slight delay. The MAPL changes are themselves ok, but they fail the CI tests because of nec

I think the CI should now be okay in MAPL (or, rather, in FV3).

2020-12-09 00:50 UTC, sanAkel commented
> > Sorry - there is a slight delay. The MAPL changes are themselves ok, but they fail the CI tests because of nec
> 
> 
> 
> I think the CI should now be okay in MAPL (or, rather, in FV3).

In that case @mathomp4 is everything _ready_?

2020-12-09 13:06 UTC, mathomp4 commented
> > > Sorry - there is a slight delay. The MAPL changes are themselves ok, but they fail the CI tests because of nec
> > 
> > 
> > I think the CI should now be okay in MAPL (or, rather, in FV3).
> 
> In that case @mathomp4 is everything _ready_?

I believe so, I assume you/Weiyuan have run the model with the changes?

2020-12-09 17:46 UTC, sanAkel commented
> > > > Sorry - there is a slight delay. The MAPL changes are themselves ok, but they fail the CI tests because of nec
> > > 
> > > 
> > > I think the CI should now be okay in MAPL (or, rather, in FV3).
> > 
> > 
> > In that case @mathomp4 is everything _ready_?
> 
> I believe so, I assume you/Weiyuan have run the model with the changes?

@weiyuan-jiang or @yvikhlya if you have indeed run the model with **ALL** the changes, would you be able to please test zero-diff with the most recent develop version? 

My guess is that these changes need to be merged with the develop, if not already.

You can see what we test:
- Coupled model https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382#issuecomment-733187697
- Uncoupled model https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382#issuecomment-733224885

Please let us know if you need help. Thanks!

2020-12-11 19:03 UTC, yvikhlya commented
This branch is zero diff with main on GEOSgcm.

2020-12-11 21:12 UTC, sanAkel commented
> This branch is zero diff with main on GEOSgcm in MOM5/MOM6 modes.

what about `develop` https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/develop ?

2020-12-11 22:39 UTC, yvikhlya submitted a review, later dismissed

2020-12-11 23:25 UTC, sanAkel submitted a review, later dismissed
following @yvikhlya 's go ahead!

2021-01-07 17:18 UTC, sanAkel commented
Hi All, @weiyuan-jiang @tclune @yvikhlya 
Is everything ready here? 

I see https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/377#pullrequestreview-526684781 was this taken care of?

2021-01-07 20:19 UTC, mathomp4 commented
Note: This is contingent on MAPL 2.5.0 being released and accepted for GEOS in `components.yaml`. I'll try and get a release of MAPL tomorrow and make a PR in GEOSgcm, but it'll take a bit of time to work through the process.

2021-01-12 18:27 UTC, mathomp4 commented
So, I just tried running GEOS (v10.17.1, I guess) with this branch and MAPL 2.5.0. The AMIP runs seem happy, but when I tried MOM6 I got failures with both Intel and GCM. In both cases I removed the `LD_PRELOAD` from `gcm_run.j`.

First, with Intel I got:
```
 CICE MPI evp initialized
 CICE MPI coupler flux initialized
 Character Resource Parameter: CICE_ADVECTION:remap
  USE Incremental Remapping for transport
 CICE MPI transport initialized
 Integer*4 Resource Parameter: CICE_NDYN_DT:1
 Real*4 Resource Parameter: OCEAN_DT:450.000000


FATAL from PE    26: Unit 9 is already in use (etc_unit) in mpp_comm_mpi

Abort(1) on node 26 (rank 26 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 26
```
GNU actually dies in a earlier place (I think reading `vegdyn`???):
```
 Character Resource Parameter: LANDICE_INTERNAL_RESTART_FILE:landice_internal_rst
 Using parallel NetCDF for file: landice_internal_rst
 Character Resource Parameter: VEGDYN_INTERNAL_RESTART_FILE:vegdyn.data
 NOT using buffer I/O for file: vegdyn.data
pe=00024 FAIL at line=01318    MAPL_IO.F90                              <status=5001>
pe=00024 FAIL at line=00983    MAPL_IO.F90                              <status=5001>
pe=00025 FAIL at line=01318    MAPL_IO.F90                              <status=5001>
pe=00025 FAIL at line=00983    MAPL_IO.F90                              <status=5001>
...
The full grep for `pe=00024` is:
```
pe=00024 FAIL at line=01318    MAPL_IO.F90                              <status=5001>
pe=00024 FAIL at line=00983    MAPL_IO.F90                              <status=5001>
pe=00024 FAIL at line=05853    MAPL_Generic.F90                         <status=5001>
pe=00024 FAIL at line=01634    MAPL_Generic.F90                         <unknown error>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01504    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01504    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01504    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01504    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01504    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=01849    MAPL_Generic.F90                         <needs informative message>
pe=00024 FAIL at line=00610    MAPL_CapGridComp.F90                     <status=1>
pe=00024 FAIL at line=00903    MAPL_CapGridComp.F90                     <status=1>
pe=00024 FAIL at line=00358    MAPL_Cap.F90                             <status=1>
pe=00024 FAIL at line=00215    MAPL_Cap.F90                             <status=1>
pe=00024 FAIL at line=00160    MAPL_Cap.F90                             <status=1>
pe=00024 FAIL at line=00134    MAPL_Cap.F90                             <status=1>
pe=00024 FAIL at line=00032    GEOSgcm.F90                              <status=1>
```
with some:
```
LANDInitialize                                1497
SURFACEInitialize                             3294
```
thrown in. I'm going to build with `Debug` and see what I see.
```

2021-01-12 18:34 UTC, sanAkel commented
Thanks @mathomp4 I was about to ask for some _details_ on 
```
FATAL from PE    26: Unit 9 is already in use (etc_unit) in mpp_comm_mpi

Abort(1) on node 26 (rank 26 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 26
```

Hopefully debug will point to something...

I recall that error with GNU (whenever we were trying debug intel 19.3.x). Not sure what is the problem. @yvikhlya could you please help?

2021-01-12 18:48 UTC, mathomp4 commented
I just fixed my last comment. Bad markdown!

2021-01-12 18:54 UTC, yvikhlya commented
I did not test this with GNU fortran. Intel was working fine after applying patches with less strict debug options.

2021-01-12 19:03 UTC, mathomp4 commented
Well, the `Debug` runs of Intel and GNU die in exactly the same way with no extra info. Maybe I'm setting MOM6 up incorrectly? 🤷🏼‍♂️

2021-01-12 19:06 UTC, yvikhlya commented
> Well, the `Debug` runs of Intel and GNU die in exactly the same way with no extra info. Maybe I'm setting MOM6 up incorrectly? 🤷🏼‍♂️

I have to repeat these tests then. Could you post your `mepo status`?

2021-01-12 19:53 UTC, mathomp4 commented
Here is my `mepo status`:
```console
$ mepo status
Checking status...
GEOSgcm                | (b) main
env                    | (t) v3.1.3 (DH)
cmake                  | (t) v3.3.5 (DH)
ecbuild                | (t) geos/v1.0.6 (DH)
NCEP_Shared            | (t) v1.1.1 (DH)
GMAO_Shared            | (t) v1.3.5 (DH)
MAPL                   | (t) v2.5.0 (DH)
FMS                    | (t) geos/2019.01.02+noaff.3 (DH)
GEOSgcm_GridComp       | (b) feature/wjiang/mom_dso
FVdycoreCubed_GridComp | (t) v1.2.9 (DH)
fvdycore               | (t) geos/v1.1.3 (DH)
GEOSchem_GridComp      | (t) v1.4.1 (DH)
mom                    | (t) geos/5.1.0+1.1.1 (DH)
mom6                   | (t) geos/v1.1.0 (DH)
GEOSgcm_App            | (b) develop
UMD_Etc                | (t) v1.0.3 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```

2021-01-12 19:54 UTC, mathomp4 commented
Essentially I ran:
```
 mepo develop GEOSgcm_GridComp GEOSgcm_App
 mepo checkout v2.5.0 MAPL
 mepo checkout feature/wjiang/mom_dso GEOSgcm_GridComp
```
after the initial `mepo clone`.

2021-01-12 20:05 UTC, mathomp4 commented
Note that @sdrabenh did update GEOSgcm after this, but the updates were outside of anything the DSO should care about (GMAO_Shared, etc.) I think.

2021-01-13 12:24 UTC, mathomp4 commented
Per a request by @sanAkel, I ran GEOSgcm without updating GEOSgcm_GridComp to this branch (so just `develop`). And that does run just fine with my "usual" MOM6 setup.

2021-01-29 18:24 UTC, weiyuan-jiang commented
With MAPL v2.5.0, it is fine to build this branch. If the results are fine, then this PR is ready to merge.  @sanAkel

2021-01-29 20:44 UTC, sanAkel commented
> With MAPL v2.5.0, it is fine to build this branch. If the results are fine, then this PR is ready to merge. @sanAkel

👍 Thank you @weiyuan-jiang will test this next week.

2021-02-16 20:12 UTC, sanAkel commented
@weiyuan-jiang, @tclune, @mathomp4 @GEOS-ESM/mapl-team updating on this PR:

I used `develop` as of 02/16/2021 (https://github.com/GEOS-ESM/GEOSgcm_GridComp/commit/0e7ac3e439d027970c875c6ff0eefea3495cd367)

These updates do not work! 😞  Please see below.

I have a:
1. debug build (as we all agreed, debug works as of now, and any change must keep that functionality intact) at `/discover/nobackup/sakella/geosMom6/develop_16Feb2021/GEOSgcm/build-Debug377` 
2. the corresponding debug build with develop (https://github.com/GEOS-ESM/GEOSgcm_GridComp/commit/0e7ac3e439d027970c875c6ff0eefea3495cd367) is at `/discover/nobackup/sakella/geosMom6/develop_16Feb2021/GEOSgcm/build-Debug`

The corresponding log files are at 
- for above 1: `/discover/nobackup/sakella/LOGS/DSO_PR_377/pr377/log.debug377`
- for above 2: `/discover/nobackup/sakella/LOGS/DSO_PR_377/develop/log.debug_mom5`

My scratch dir (testing with MOM5) is at `/discover/nobackup/sakella/test_m5` 

@weiyuan-jiang since this is your branch, would you please look into it. Thanks!

2021-02-16 20:56 UTC, mathomp4 commented
More info for @weiyuan-jiang, if I use the traceback workaround:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
GEOSgcm.x          00000000036B6BFA  Unknown               Unknown  Unknown
libpthread-2.22.s  00002AAABBE5DC10  Unknown               Unknown  Unknown
GEOSgcm.x          0000000003798463  Unknown               Unknown  Unknown
GEOSgcm.x          000000000371DCBC  Unknown               Unknown  Unknown
libMAPL.base.so    00002AAAB30E57EE  mapl_genericmod_m        4801  MAPL_Generic.F90
GEOSgcm.x          000000000341B785  guestocean_gridco         124  GuestOcean_GridComp.F90
```
which points to:
```fortran
  META%GCNameList(I) = trim(FNAME)
```
So maybe the name got mangled?

2021-02-17 14:17 UTC, mathomp4 commented
To try and get the Intel traceback, add:
```
ml mpi/impi-prov/19.1.3.304
```
just before you run `GEOSgcm.x` in `gcm_run.j`

2021-02-17 14:34 UTC, sanAkel commented
> To try and get the Intel traceback, add:
> 
> ```
> ml mpi/impi-prov/19.1.3.304
> ```
> 
> just before you run `GEOSgcm.x` in `gcm_run.j`

Thanks @mathomp4 do we need it **always**? like the gcm_run.j that's off the `develop` GEOSgcm_App?

2021-02-17 15:01 UTC, mathomp4 commented
> > To try and get the Intel traceback, add:
> > ```
> > ml mpi/impi-prov/19.1.3.304
> > ```
> > 
> > 
> > just before you run `GEOSgcm.x` in `gcm_run.j`
> 
> Thanks @mathomp4 do we need it **always**? like the gcm_run.j that's off the `develop` GEOSgcm_App?

I haven't put it in `g5_modules` because technically, this could lead to slower code on the Haswells (it's "degrading" the networking provider). And sometimes, you never see an issue with it. But when you do see the GNU traceback with Intel, it usually fixes it.

2021-02-17 15:05 UTC, mathomp4 commented
Note: After updating FMS to the `feature/wjiang/mom_dso` I get the same crash and traceback with MOM6 using `Release` build.

2021-02-17 15:08 UTC, sanAkel commented
> Note: After updating FMS to the `feature/wjiang/mom_dso` I get the same crash and traceback with MOM6 using `Release` build.

I didn't ask it in our 9AM meeting, but hopefully whatever @weiyuan-jiang is wanting to have in `feature/wjiang/mom_dso` won't conflict or interference with `FMS2` which are looking forward 😮 to?!

2021-02-17 17:39 UTC, sanAkel commented
@weiyuan-jiang @mathomp4 @tclune 

I just finished making 2 runs with MOM5 and `develop`.

- My logs are at: `/discover/nobackup/sakella/LOGS/DSO_PR_377/develop`
- Output for:
  - **debug** build (run for `1` hour):    `/discover/nobackup/sakella/test_m5/`**scratch_debug_develop**
  - **optim** build  (run for `6` hours):  `/discover/nobackup/sakella/test_m5/`**scratch_optim_develop**

Based on our conversation in the morning, I am expecting @weiyuan-jiang would run with his changes, both debug and optim, So it would be real easy to `cmp` or `cdo diff` his output with mine as ⤴️  Or else, once @weiyuan-jiang you have the 2 runs with debug (1 hour) and optim (6 hours), tell me where your output is.

I don't expect debug output to be zero-diff. My experiment is at `/discover/nobackup/sakella/test_m5/`

2021-02-18 18:03 UTC, mathomp4 commented
Weiyuan made a change to MAPL that I've been testing. With that update I can confirm that I can run MOM5 and MOM6 with this branch. I also used his FMS update (which is now tagged as `geos/2019.01.02+noaff.4`) as well as hand editing `gcm_setup`. (To make that last step easier, I've created a `feature/wjiang/mom_dso` branch on GEOSgcm_App and made a draft PR: https://github.com/GEOS-ESM/GEOSgcm_App/pull/204 )

The tests I ran were:

- [x] MOM6 Release
  - [x] Zero-diff
- [x] MOM5 Release
  - [x] Zero-diff
- [X] MOM6 Debug
   - [ ] Zero-diff 
- [X] MOM5 Debug
   - [X] Zero-diff 

I *do not* know why the MOM6 debug is non-zero-diff, but it seems to be for me. But I might have screwed something up. @sanAkel might need to do his own testing. Very highly possible I screwed it up 

I also then tried running at NAS with MPT with these updates
- [x] MOM6 MPT NAS
- [X] MOM5 MPT NAS

2021-02-18 21:53 UTC, sanAkel commented
Adding summary from my testing:

### Coupled Model Testing

#### With respect to `develop` (https://github.com/GEOS-ESM/GEOSgcm/commit/0922ecb6a54bd90ce37d15b2a903bf24f1967fa7) on Feb 17, 2021

- Logs are at: `/discover/nobackup/sakella/LOGS/DSO_PR_377/`

- **debug**  Run for 1 hour (450 s time step). 
    - ✔️  MOM5 and is **zero-diff* to ⤴️ `develop` @mathomp4 I `cmp RESTART/ocean_temp_salt.res.nc`
    - ✔️  MOM6 is **not** zero-diff to ⤴️ `develop` Diff in `Temp, Salt, h, v, ...` is in 3rd decimal digits; for some reason(!!) `frazil, uh, vh, uhbt_IC, vhbt_IC` have bigger differences. But we do not _expect_ zero-diff for debug build!

- **optim**  Run for 6 hours (450 s time step) and is **zero-diff* to ⤴️ `develop`
    - ✔️  MOM5 
    - ✔️  MOM6

(@sdrabenh  no more boxes with _incorrect_ status of check boxes 😞 ) 

**what did I do?**
1. followed @mathomp4's instructions:
  `mepo clone -b feature/wjiang/mom_dso git@github.com:GEOS-ESM/GEOSgcm.git`
2. build optimized and debug versions
3. run for the above time periods and `cmp` corresponding `fvcore_internal_checkpoint` and `RESTART/ocean_temp_salt.res.nc` (for MOM5) and `RESTART/MOM.res.nc` (for MOM6).

**mepo status** (from above 1)
```
GEOSgcm                | (b) feature/wjiang/mom_dso
env                    | (t) v3.1.3 (DH)
cmake                  | (t) v3.3.6 (DH)
ecbuild                | (t) geos/v1.0.6 (DH)
NCEP_Shared            | (t) v1.1.1 (DH)
GMAO_Shared            | (t) v1.3.8 (DH)
MAPL                   | (b) hotfix/wjiang/addChildfromDSO (DH)
FMS                    | (t) geos/2019.01.02+noaff.4 (DH)
GEOSgcm_GridComp       | (b) feature/wjiang/mom_dso (DH)
FVdycoreCubed_GridComp | (t) v1.2.9 (DH)
fvdycore               | (t) geos/v1.1.3 (DH)
GEOSchem_GridComp      | (t) v1.4.1 (DH)
mom                    | (t) geos/5.1.0+1.1.1 (DH)
mom6                   | (t) geos/v1.1.0 (DH)
GEOSgcm_App            | (b) feature/wjiang/mom_dso (DH)
UMD_Etc                | (t) v1.0.3 (DH)
CPLFCST_Etc            | (t) v1.0.1 (DH)
```
#### Note:
- `gcm_run.j` should **not** have `LD_PRELOAD`
- log file should echo: 
  - for `MOM5`: Character Resource Parameter: `MOM_GEOS5PLUGMOD:libMOM_GEOS5PlugMod.so` 
  - for `MOM6`: Character Resource Parameter: `MOM6_GEOSPLUG:libMOM6_GEOSPlug.so`

2021-02-18 22:13 UTC, sanAkel approved these changes
Good to go! 

@sdrabenh

2021-02-19 13:25 UTC, mathomp4 commented
For @sdrabenh Note that this PR must be taken at the same time with https://github.com/GEOS-ESM/GEOSgcm_App/pull/204

There are other PRs needed for overall functioning--MAPL 2.6.2 and FMS noaff4--but they can independently be taken at any time.

2021-02-22 17:04 UTC, sanAkel commented
@mathomp4, @sdrabenh (@weiyuan-jiang , @tclune) 

Is following list accurate for what has been **merged** `(✔️)`  or **not yet** `(❌)`? 

If not please modify. Thanks! 

- ❌  or ✔️ MAPL                   | (b) hotfix/wjiang/addChildfromDSO (DH)
- ❌  or ✔️FMS                    | (t) geos/2019.01.02+noaff.4 (DH)
- ❌  or ✔️ GEOSgcm_App            | (b) feature/wjiang/mom_dso (DH)
- ❌ or ✔️ GEOSgcm_GridComp       | (b) feature/wjiang/mom_dso (DH)

2021-02-22 18:19 UTC, weiyuan-jiang commented
I removed DNA label. Hopefully it will be merged soon

2021-02-22 18:32 UTC, sanAkel commented
> @mathomp4, @sdrabenh (@weiyuan-jiang , @tclune)
> 
> Is following list accurate for what has been **merged** `(✔️)` or **not yet** `(❌)`?
> 
> If not please modify. Thanks!
> 
> * ❌ MAPL -- Tagged as `v2.6.2`, PR here: [GEOS-ESM/GEOSgcm#253](https://github.com/GEOS-ESM/GEOSgcm/pull/253)
> * ❌ FMS -- Tagged as `geos/2019.01.02+noaff.4`, PR: [GEOS-ESM/GEOSgcm#254](https://github.com/GEOS-ESM/GEOSgcm/pull/254)
> * ❌  or ✔️ GEOSgcm_App            | (b) feature/wjiang/mom_dso (DH)
> * ❌ or ✔️ GEOSgcm_GridComp       | (b) feature/wjiang/mom_dso (DH)
> 
> Edited by @mathomp4

Thanks @mathomp4 Did you mean to say, first two: `MAPL` and `FMS` are merged?

2021-02-22 18:45 UTC, mathomp4 commented
@weiyuan-jiang The Contingent label was there because this is contingent on having the MAPL PR merged as well as the GEOSgcm_App PR must be taken at the same time!

2021-03-02 17:42 UTC, tclune approved these changes

2021-03-02 17:43 UTC, merged