New MOM6 configuration (OM4), bug fix in MOM6_Plug
GEOS-ESM/GEOSgcm_GridComp pull request #385
Opened 2020-11-27 16:06 UTC by yvikhlya

Fixes #384

2020-11-27 18:46 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
> +This configuration was adapted from MOM6-examples/ocean_only/global_ALE/z.
This line does not seem right! Please _correct source_.

2020-11-27 18:48 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
> -       sea_lev = real(merge(tsource = Tmp2, fsource = real(MAPL_UNDEF), mask = (MASK(:, :) > 0.0)), kind=G5KIND)
Please have a comment to the effect that:
sea_lev init is from sea ice restart

2020-11-27 18:49 UTC, yvikhlya commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
> +This configuration was adapted from MOM6-examples/ocean_only/global_ALE/z.
Yes, this is right. This is ocean_only/global_ALE configuration.

2020-11-27 18:50 UTC, yvikhlya commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/MOM6_GEOSPlug.F90
> -       sea_lev = real(merge(tsource = Tmp2, fsource = real(MAPL_UNDEF), mask = (MASK(:, :) > 0.0)), kind=G5KIND)
Comment is in commit message.

2020-11-27 18:58 UTC, sanAkel requested changes

2020-11-27 18:58 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_override
> +DO_DYNAMICS = False
comment out:

>DO_DYNAMICS = False

2020-11-27 18:58 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/README.md
> +This configuration was adapted from MOM6-examples/ice_ocean_SIS2/OM_1deg/MOM_input.
Instead of `MOM6-examples/ice_ocean_SIS2/OM_1deg/MOM_input` please have `URL`. Thanks!

2020-11-27 19:01 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
> +This configuration was adapted from MOM6-examples/ocean_only/global_ALE/z.
👍  I updated my comment.

2020-11-27 19:03 UTC, yvikhlya commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
> +This configuration was adapted from MOM6-examples/ocean_only/global_ALE/z.
URLs added.

2020-11-27 19:04 UTC, yvikhlya commented on GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_override
> +DO_DYNAMICS = False
Oh shh, forgot to remove this.

2020-11-27 19:37 UTC, sanAkel approved these changes
All requested changes have been made, Thank you @yvikhlya . Can be merged once we confirm status of debug and release builds for new grid, in 1- 3 configurations listed at https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/384#issue-751952764

2020-11-30 15:51 UTC, zhaobin74 commented
CICE grid file (grid_cice.bin) was fixed by setting a lower limit (>0) in the HTE field such that CICE remap advection routine will not trigger divide by zero error.

2020-12-03 22:20 UTC, yvikhlya commented
OM4 configuration crashes in debug mode. Probably this should be a different issue.

2020-12-03 22:20 UTC, sanAkel approved these changes

2020-12-03 22:21 UTC, sanAkel commented
> OM4 configuration crashes in debug mode. Probably this should be a different issue.

True! We can proceed with it for now.

2021-01-12 14:53 UTC, sdrabenh approved these changes

2021-01-12 15:25 UTC, merged