Fixes bug in SaltWater when OceanBioGeoChem is enabled
GEOS-ESM/GEOSgcm_GridComp pull request #401
Opened 2021-01-20 22:01 UTC by gmao-esherman

If "USE_OCEANOBIOGEOCHEM:1", then the SEASALT gridded component will fail looking for exports from OBIO, which do not exist. A condition has been put in place that checks the name of SEASALT's children for "OBIO" and only retrieves the exports/pointers if the child is not OBIO.

2021-01-20 22:08 UTC, yvikhlya commented
I do not understand how this is all related to obio? Is this a problem because obio is meant to run with data atmosphere instead of agcm?

2021-01-20 22:41 UTC, gmao-esherman commented
> I do not understand how this is all related to obio? Is this a problem because obio is meant to run with data atmosphere instead of agcm?

No, I don't think this is an issue with Obio running with data atmosphere.

There is a gridded component called Obio (GEOS_ObioGridComp.F90) that is a child of Seawater. When "USE_OCEANBIOGOECHEM:1" it enables this Obio component and it is "born". It is confusing because there is another Obio that is a child of OGCM. The Obio that is the child of the OGCM is from GEOS_OceanbiogeochemGridComp.F90.

GEOS_SaltWaterGridComp.F90 loops over size(GCS) (where GCS are the children's gridded components) and retrieves pointers. If Obio is "born", Saltwater tries to retrieve exports/pointers that Obio does not have and the model crashes.

2021-01-20 23:10 UTC, sanAkel commented
> > I do not understand how this is all related to obio? Is this a problem because obio is meant to run with data atmosphere instead of agcm?
> 
> No, I don't think this is an issue with Obio running with data atmosphere.
> 
> There is a gridded component called Obio (GEOS_ObioGridComp.F90) that is a child of Seawater. When "USE_OCEANBIOGOECHEM:1" it enables this Obio component and it is "born". It is confusing because there is another Obio that is a child of OGCM. The Obio that is the child of the OGCM is from GEOS_OceanbiogeochemGridComp.F90.
> 
> GEOS_SaltWaterGridComp.F90 loops over size(GCS) (where GCS are the children's gridded components) and retrieves pointers. If Obio is "born", Saltwater tries to retrieve exports/pointers that Obio does not have and the model crashes.

@gmao-esherman rather than _born_ may be we should say, _instantiated_?

2021-01-20 23:21 UTC, sanAkel commented
@gmao-esherman as you said okay to it, I will push a few changes to the surface GC. Once all together, we just have to do a few quick checks: https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/382#issuecomment-733187697 Since you already have the `default` run with `USE_OCEANOBIOGEOCHEM:0` I suggest please keep it _alive_! Thanks! It will come handy for zero-diff testing. We can skip testing with one of the ocean models. From your exp dir: `/gpfsm/dnb32/esherman/coupled_obio` I see you tested with `MOM5` ocean model, so in the check list we can skip `MOM6`.

2021-01-20 23:21 UTC, gmao-esherman commented
> > > I do not understand how this is all related to obio? Is this a problem because obio is meant to run with data atmosphere instead of agcm?
> > 
> > 
> > No, I don't think this is an issue with Obio running with data atmosphere.
> > There is a gridded component called Obio (GEOS_ObioGridComp.F90) that is a child of Seawater. When "USE_OCEANBIOGOECHEM:1" it enables this Obio component and it is "born". It is confusing because there is another Obio that is a child of OGCM. The Obio that is the child of the OGCM is from GEOS_OceanbiogeochemGridComp.F90.
> > GEOS_SaltWaterGridComp.F90 loops over size(GCS) (where GCS are the children's gridded components) and retrieves pointers. If Obio is "born", Saltwater tries to retrieve exports/pointers that Obio does not have and the model crashes.
> 
> @gmao-esherman rather than _born_ may be we should say, _instantiated_?

Yes! Instantiate is a much clearer word to use.

2021-01-22 02:52 UTC, sanAkel commented
@gmao-esherman since this feature of `USE_OCEANOBIOGEOCHEM:1` does not **yet** work with the code changes (as of 01/21) would you please draft this PR, so @sdrabenh  gets notified. Thanks!

2021-01-22 13:54 UTC, gmao-esherman commented
> @gmao-esherman since this feature of `USE_OCEANOBIOGEOCHEM:1` does not **yet** work with the code changes (as of 01/21) would you please draft this PR, so @sdrabenh gets notified. Thanks!

Agreed, done!

2021-01-22 14:59 UTC, yvikhlya commented
Normally, we submit a PR when a code is actually working, passes all tests and ready to be merged with develop. We don't want to have a disfunctional code in develop, right? Until then work can be done on a long live feature branch. I would suggest to make a branch something like feature/obio and accumulate all bug fixes there until this feature actually works, then make a PR.

2021-01-22 15:02 UTC, gmao-esherman commented
> Normally, we submit a PR when a code is actually working, passes all tests and ready to be merged with develop. We don't want to have a disfunctional code in develop, right? Until then work can be done on a long live feature branch. I would suggest to make a branch something like feature/obio and accumulate all bug fixes there until this feature actually works, then make a PR.

I agree. There was some initial confusion on my part of what this PR was supposed to be. I have since taken @sanAkel's suggestion and made this PR a draft.

2021-02-17 14:37 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
> + wspd = 0.0
@gmao-esherman I know nothing about this code part of the model, but, `wspd` values of > 1000.? Something is wrong somewhere **else**! 

Simply resetting to `0.0` is bypassing the problem!

2021-02-17 15:16 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
> + wspd = 0.0
Yes I agree. This is NOT a permanent solution. The issue is with the 'UU' variable (where the pointer is WSD) in GEOS_OradBioGridComp. WSD has at least one value of 1.0E14 that causes the model to crash in the clrtrans subroutine. We can filter out the bad value(s) in the line of code below. It's just a question of how.

https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/31d9619259ce92f0a6b72a6906e81e4a38e1351b/GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90#L939

Maybe something like...
`if (WSM(i,j) == 1.0E14) then cycle`
`else`
`wspd = WSM(i,j)`
`end if`

Whatever fix we apply, we should also apply to GEOS_OceanbiogeochemGridComp.F90. I am not sure why the kloop didn't crash with the same bad wind speed.
https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/31d9619259ce92f0a6b72a6906e81e4a38e1351b/GEOSogcm_GridComp/GEOS_OceanBioGeoChemGridComp/GEOS_OceanbiogeochemGridComp.F90#L1324

2021-02-17 15:19 UTC, yvikhlya commented
> WSD has at least one value of 1.0E14 that causes the model to crash in the clrtrans subroutine.

This looks like a wrong land-sea mask.

2021-02-18 20:55 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +do i = 1, ubound(UU,1)
these should come off. Good for debugging, but not leave stuff like this!

2021-02-18 20:56 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +end do
same as above, please take them off.

2021-02-18 20:57 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
> +if(mapl_am_i_root()) print*,'SALTWATER size(UU) = ',size(UU)
same as above

2021-02-18 20:57 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
> +do i = 1, ubound(UU,1)
same as above

2021-02-18 20:57 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +do k = 1, ubound(UU,1)
same as above

2021-02-18 20:58 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
> +       if ((slp < 0.0 .or. slp >1.0E10) .or. (wspd == MAPL_UNDEF)) then ! extended to include condition for wspd, EMS
I would say do it wholesale for all variables!

2021-02-18 20:59 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
>        if (wspd .gt. 4.0)then
things like `4.0` and `7.0` does not look good!

2021-02-18 21:00 UTC, sanAkel reviewed
@gmao-esherman please comments. 

Please take print statements off. Thanks!

2021-02-18 21:06 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/clrtrans.F90
>        if (wspd .gt. 4.0)then
Agreed. This is part of the original code. I did not write this.

2021-02-18 21:07 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OradBioGridComp/GEOS_OradBioGridComp.F90
> +       if ((slp < 0.0 .or. slp >1.0E10) .or. (wspd == MAPL_UNDEF)) then ! extended to include condition for wspd, EMS
will do.

2021-02-18 21:07 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +do k = 1, ubound(UU,1)
Yes, I will remove all of the debugging statements.

2021-02-28 21:23 UTC, sanAkel commented
@gmao-esherman Can https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/400 be _fixed_ ? by making whatever changes are needed?

2021-03-15 15:48 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
>     do I = 1, size(GCS)
@gmao-esherman please add comment before the **first**
```
do I = 1, size(GCS)
...
```

to imply the following: "get pointers to exports from all children, other than OBIO"

and before the **second** do loop, the comment could be: "get pointers to exports from OBIO child"

2021-03-15 15:51 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +       OBIO = MAPL_AddChild(GC, NAME='OBIOtest', SS=ObioSetServices, RC=STATUS)
@gmao-esherman `OBIOtest` is going to be changed to some other name of your choice, right?

2021-03-15 15:54 UTC, sanAkel requested changes
This PR can be merged with suggested comments added. 

Thank you @sdrabenh

2021-03-15 16:02 UTC, sanAkel commented
this PR would also:
- fix https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/394
- fix https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/395

essentially it _seems_ to include all changes from https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/396 @gmao-esherman not sure how you pooled all those changes!

2021-03-15 16:07 UTC, gmao-esherman commented
> this PR would also:
> 
>     * fix #394
> 
>     * fix #395
> 
>     * fix #400
> 
> 
> essentially it _seems_ to include all changes from #396 @gmao-esherman not sure how you pooled all those changes!

I am pretty sure I merged in Atanas' bugfix branch into mine a little while back.

2021-03-15 16:15 UTC, yvikhlya commented
> > this PR would also:
> > ```
> > * fix #394
> > 
> > * fix #395
> > 
> > * fix #400
> > ```
> > 
> > 
> > essentially it _seems_ to include all changes from #396 @gmao-esherman not sure how you pooled all those changes!
> 
> I am pretty sure I merged in Atanas' bugfix branch into mine a little while back.

Yes, I see the related commits. This is good. #396 can be closed then.

2021-03-15 17:53 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +       OBIO = MAPL_AddChild(GC, NAME='OBIOtest', SS=ObioSetServices, RC=STATUS)
Yes. I will change `OBIOtest` to `OBIO_OGCM`.

2021-03-15 18:12 UTC, gmao-esherman commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
>     do I = 1, size(GCS)
What second do loop are you referring to?

2021-03-15 18:32 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
>     do I = 1, size(GCS)
My bad, there is only one!

2021-03-15 21:06 UTC, gmao-esherman commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
>     do I = 1, size(GCS)
I have added that comment in my latest commit.

2021-03-15 21:07 UTC, gmao-esherman commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +       OBIO = MAPL_AddChild(GC, NAME='OBIOtest', SS=ObioSetServices, RC=STATUS)
The above mentioned change is included in my latest commit.

2021-03-15 22:36 UTC, sanAkel approved these changes

2021-03-18 19:44 UTC, sdrabenh approved these changes

2021-03-18 19:44 UTC, merged