Feature/atrayano/#169 add datalake
GEOS-ESM/GEOSgcm_GridComp pull request #557
Opened 2022-03-01 20:23 UTC by atrayano

This PR adds a DataLake implementation in GEOS. It is zero-diff when the DataLake feature is not exercised (default), otherwise expect non-zero differences

2022-03-01 21:58 UTC, gmao-rreichle submitted a review, later dismissed

2022-03-16 16:53 UTC, sanAkel commented
https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/169#issuecomment-1069339597

2022-03-16 23:41 UTC, sanAkel commented
@atrayano, @sdrabenh,

You may find following instructions to generate a mask for the Great Lakes and Caspian sea and (binary) SST and Sea Ice concentration helpful.

## Steps to generate a lake _mask_ and data for a given date

   In the following example, date is set to: **2022/01/01**

0. Set modules: source GEOSgcm/@env/g5_modules
1. Generate an input file `input.txt`
   - One can find `gen_input.csh` at:
     ```
     GEOSgcm/src/Shared/@GMAO_Shared/GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/
     ```
   - Change year `2020` to `2022`, i.e., line:
     https://github.com/GEOS-ESM/GMAO_Shared/blob/5b864daa4e41df596e4b385cd61da57e0f69f97b/GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/gen_input.csh#L65
     to:
     ```
     set reynolds_data_loc = '/gpfsm/dnb42/projects/p17/production/GEOS5odas-5.00/RC/OBS/REYN/2022/'
     ```
   - Use `gen_input.csh 2022 1 1 OSTIA`. Attached is the generated `input.txt` if you do not _run_ `gen_input.csh` 
2. Generate data and lake mask:
   ```
   GEOSgcm/install/bin/lake_sst_sic_EIGTHdeg.x input.txt
   ```

   All goes okay, you should get:
   ```
   Data over Great Lakes and Caspian Sea
   Processing SST and ICE data from: 20220101...To... 20220102
   ...Finished!
   ```
   and three binary files: `mask.bin, Ostia_ice_20220101.bin  Ostia_sst_20220101.bin`
3. Note that these three binary files are of the same size, each contains a two-dimensional field (mask, sst or sea ice concentration),
   at a regular 1/8-deg (lat-lon) grid (date-line edge, pole edge). One can use [plot_bcs.py](https://gist.github.com/sanAkel/8845edab405c4a8ee934acacaa924a53) to plot:
   ```
   plot_bcs.py -data_path /discover/nobackup/sakella/TMP/nn -year 2022 -month 1 -day 1
   ```

[input.txt](https://github.com/GEOS-ESM/GEOSgcm_GridComp/files/8275836/input.txt)
![bcs_SST_SIC_20220101](https://user-images.githubusercontent.com/18061653/158708766-067b8482-fba5-401b-9bea-5c5f683c7333.png)

2022-03-22 15:01 UTC, sdrabenh commented
@atrayano just checking on your timetable for generating the new raster/tile files reverting the lakes to lakes? Obviously I can't test anything further until that happens.

2022-03-22 15:05 UTC, atrayano commented
Scott,
Thanks for your e-mail (this was a perfect reminder!).
I am planning to generate these files myself and test the PR myself first, before I pass it to you for further testing. Hopefully this won’t take too long, and I’ll be ready sometime this week…

Atanas

From: Scott Rabenhorst ***@***.***>
Reply-To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Date: Tuesday, March 22, 2022 at 11:01 AM
To: GEOS-ESM/GEOSgcm_GridComp ***@***.***>
Cc: "Trayanov, Atanas L. (GSFC-610.1)[SCIENCE SYSTEMS AND APPLICATIONS INC]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GEOSgcm_GridComp] Feature/atrayano/#169 add datalake (PR #557)


@atrayano<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fatrayano&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7Ca65724589752482fbf0808da0c14d079%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637835580778986921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n69pL3Uq6Cd676pEWF57WmjdkI1YWkBNMqT4sE7V2JA%3D&reserved=0> just checking on your timetable for generating the new raster/tile files reverting the lakes to lakes? Obviously I can't test anything further until that happens.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGEOSgcm_GridComp%2Fpull%2F557%23issuecomment-1075292645&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7Ca65724589752482fbf0808da0c14d079%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637835580778986921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ajz%2BtEdIBeQaSEEqnAWmnaexpx7Vb7tG5DNZ4AiUBZg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL6ZCVL2U5VEVAXTXDF5IDLVBHODTANCNFSM5PVCEP4Q&data=04%7C01%7CAtanas.L.Trayanov%40nasa.gov%7Ca65724589752482fbf0808da0c14d079%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637835580778986921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Nr%2BxACefGyO5ckzYHZlVZSm%2FKjR0Az%2FizuZ1lupOSQM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-03-22 15:09 UTC, sdrabenh commented
> Scott, Thanks for your e-mail (this was a perfect reminder!). I am planning to generate these files myself and test the PR myself first, before I pass it to you for further testing. Hopefully this won’t take too long, and I’ll be ready sometime this week… Atanas

Great, thanks. I just wanted to have a general idea of the timing. Sounds good.

2022-04-01 19:51 UTC, sanAkel requested changes

2022-04-01 19:51 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          TS(:,ICE)   = TICE
`TS(:,ICE)` needs to be set from data file, just as `SST` is being set.

This needs to be _fixed_. Thanks! 🙏

2022-04-01 19:52 UTC, sanAkel commented
@sdrabenh, @atrayano please see above for `TICE` that needs to be handles just as `SST`.

2022-04-01 19:59 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +   real, parameter :: tice = MAPL_TICE - 1.8
@sanAkel If I remember correctly, couple of year ago I had a discussion with Andrea, and TICE was her suggestion. Are you sure the ice temperature over the lakes is resolved correctly in the observed datasets? In GEOS_DataSeaGridComp.F90 we cap the SST to TICE in a similar fashion

2022-04-01 21:43 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          TS(:,ICE)   = TICE
> `TS(:,ICE)` needs to be set from data file, just as `SST` is being set.
> 
> This needs to be _fixed_. Thanks! 🙏

⬆️ is incorrect! I amend below:

```
where(mask)
 TS(:,WATER) = SST  ! from data file
  TS(:,ICE)  =  TICE ! or Tfreeze, which is the temperature where fresh water freezes, say -1.8 degC.
endwhere
```

However, I would still request that the `FR` from a dataset like the `sst.data` be also read in and we make use that `FR` where `mask = .TRUE.`

2022-04-01 23:00 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          TS(:,ICE)   = TICE
I totally agree, that adding FR similar to SST is the right thing to do

2022-04-01 23:04 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          TS(:,ICE)   = TICE
I will make the FR changes soon

2022-04-01 23:05 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          TS(:,ICE)   = TICE
🙏

2022-04-05 00:08 UTC, atrayano commented
@sanAkel The changes you requested have been committed and pushed. Could you, pease, review them. I tested them with c12, and generating data for Scott to test them with c180 and c30

2022-04-05 00:11 UTC, sanAkel commented
> @sanAkel The changes you requested have been committed and pushed. Could you, pease, review them. I tested them with c12, and generating data for Scott to test them with c180 and c360

Thanks @atrayano, will take a look at it later.

As for @sdrabenh's testing, you are referring to test with coupled or uncoupled model configuration? Latter may need that raster/tile file that reverts Great Lakes and Caspain to being lakes again.

2022-04-05 00:13 UTC, atrayano commented
This up to him. He indicated desire to test both, but for now he has asked me for 2 different resolutions ( c180 and c360) uncoupled

2022-04-05 02:24 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +       if(mystate%mask(i)) cycle
@atrayano,
probably it should be:
```
mystate%mask
```
**without** `(i)` ??

2022-04-05 02:29 UTC, sanAkel reviewed
@atrayano thanks for adding the ice fraction. Please see one question ⬆️ reg `mystate%mask(i)`

2022-04-05 03:01 UTC, sdrabenh commented
> This is up to him. He indicated desire to test both, but for now he has asked me for 2 different resolutions ( c180 and c360) uncoupled. Of course, my new tile file reflects the reverted "new" lakes

Thanks @atrayano. @sanAkel these are for the uncoupled tests just to test if everything is behaving as expected and within roundoff. However, when we meet this week I'd like to discuss what you recommend for a coupled test.

2022-04-05 13:09 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +       if(mystate%mask(i)) cycle
@sanAkel The "i" is needed at the moment. This block needs to be revisited or handled differently altogether, but not as a part of this PR

2022-04-05 18:21 UTC, atrayano commented
Pinging @sanAkel to review the PR

2022-04-05 18:48 UTC, sanAkel submitted a review, later dismissed

2022-04-05 18:48 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +       if(mystate%mask(i)) cycle
@atrayano, I don't understand why not!

2022-08-22 18:12 UTC, sdrabenh commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +        if (.not. mystate%InitDone) then
@atrayano don't we have to update the data as the run goes on?

2022-08-22 18:18 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +        if (.not. mystate%InitDone) then
@sdrabenh We keep only the mask (i.e. mapping which lake tiles we use to apply dataLake SSTs) in the private state. The mask does not change during the run, only the SST and the fractions of the lake ice

2022-08-22 18:36 UTC, sdrabenh commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          if(mystate%mask(i)) then
@atrayano are we sure this condition is actually being entered for our mask?

2022-08-22 18:40 UTC, sdrabenh commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +       where(.not.mystate%mask) TS(:,N) = TS(:,N) + DTS
@atrayano shouldn't we loop through `I=1,NT` ?

2022-08-22 18:41 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +          if(mystate%mask(i)) then
I am almost sure that we enter the block above. I am setting a debugging experiment right now...

2022-08-22 18:48 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +       where(.not.mystate%mask) TS(:,N) = TS(:,N) + DTS
The loop over NT is implicit (i.e. the tile index is the first index in TS. But we also loop over ice and water (N index)

2022-08-22 18:54 UTC, atrayano commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +  logical, intent(INOUT)           :: msk(:)
No (but this is why we had confusion with the different lake mask files). The local variable is logical, but it is set inside DatLakeReadMask (where we read a "float" and convert it to logical)

2022-08-22 18:55 UTC, sanAkel commented
@tclune, @atrayano I just looked at this PR with @sdrabenh.

The code seems to have many bugs and superfluous logic.

We recommend this PR be closed, code be **cleanly** rewritten for our consideration.

Thank you.

2023-05-10 14:17 UTC, gmao-rreichle approved these changes

2023-05-16 17:29 UTC, sdrabenh approved these changes

2023-05-16 17:31 UTC, sdrabenh approved these changes

2023-05-17 14:45 UTC, merged