long name changes & landice gc modifications to support R21C history
GEOS-ESM/GEOSgcm_GridComp pull request #664
Opened 2022-11-11 20:28 UTC by lcandre2

This pull request is paired with a PR in GEOSgcm_App and address points in [PR#637](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/637). The modifications touch the SURFACE grid comp and children including land, landice and saltwater. 
-----------------
I introduced the following changes:
1. In SURFACE, the long name/description of AICE was changed to “sea_ice_covered_fraction_of_ocean_area”  and the long name/description of FRSEAICE was changed to “sea_ice_covered_fraction_of_grid_cell” . Following discussions with several people, the long names were NOT changed in Saltwater because the reference to ‘tile’ remains correct in those instances.

2. Long name changes to ALBVF, ALBNF, ALBVR, ALBNR in which ‘reflectivity’ replaces ‘albedo’ in SURFACE and all children for consistency. This supports the inclusion of ALBVF, ALBNF in the rad collection and distinguishes them from these variables exported from ‘SOLAR’. This decision may require modifications/discussion.

3. Long name changes to RAINREFREZ (contribution_to_smb_from_rain_frozen_onto_bare_ice) and EVAPOUT (water_vapor_vertical_flux_at_glacier_surface) in LANDICE. These are landice specific exports.

4. A change in sign was applied the the GHTSKIN export from LANDICE to rectify a conflict with the variable sign in LAND. This change was confirmed with a short test. Figure included. 

Let me know if any issues arise or if there are any questions or comments. 

![balance_10d](https://user-images.githubusercontent.com/53305329/201425720-18feb8c1-3a39-4ae9-bf1b-b21ee9425b56.png)

2022-11-11 21:22 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +        LONG_NAME          = 'surface_reflectivity_for_nearinfraed_diffuse', &
FYI, there's a typo.  Missing `r` in `..._nearinfra**r**ed_...`

2022-11-11 21:24 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +        LONG_NAME          = 'surface_reflectivity_for_near_infrared_beam', &
FYI, in Surface GC it's `nearinfrared` (no underscore), here it's `near_infrared` (with underscore).  Same comment applies to line 149.

2022-11-12 16:53 UTC, sanAkel requested changes

2022-11-12 16:53 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/GEOS_LandIceGridComp.F90
> +    if(associated(GHTSKIN )) GHTSKIN = (-1.0)*(ghflxsno*FR(:,SNOW) + ghflxice*FR(:,ICE)) !changed lca 11/05/22 to align with land gc
There is no need for such "!xx..." comment line. Such comments should belong to commit message and PR description. "Git blame" can easily help associate the change with the commit message.

2022-11-14 14:46 UTC, lcandre2 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlake_GridComp/GEOS_LakeGridComp.F90
> +        LONG_NAME          = 'surface_reflectivity_for_near_infrared_beam', &
After checking all Surface's children, it seems that Surface is the outlier. I changed the Surface GC to be *_near_infrared_*. This was in the branch I checked out.

2022-11-14 14:46 UTC, lcandre2 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSlandice_GridComp/GEOS_LandIceGridComp.F90
> +    if(associated(GHTSKIN )) GHTSKIN = (-1.0)*(ghflxsno*FR(:,SNOW) + ghflxice*FR(:,ICE)) !changed lca 11/05/22 to align with land gc
Fair enough, removed.

2022-11-14 14:48 UTC, lcandre2 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +        LONG_NAME          = 'surface_reflectivity_for_nearinfraed_diffuse', &
I should have caught this even though it was a previous typo. Fixed and changed _nearinfrared_ to _near_infrared_ to be consistent with all children. Surface was the outlier here and I think it is more correct with the additional underscore.

2022-11-23 19:09 UTC, lcandre2 commented
This branch was merged into feature/rreichle/r21c_updates and changes are addressed in pull request [#637](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/637).

2022-11-23 19:09 UTC, closed without merging