Feature/adarmenov/ignio
GEOS-ESM/GEOSgcm_GridComp pull request #699
Opened 2023-02-01 18:41 UTC by adarmenov

IGNI is a new component that integrates fire weather observations into fuel moisture codes and fire behavior indexes based on the CFFWI system.

2023-02-01 18:49 UTC, sanAkel requested changes
Reviewing on behalf of @GEOS-ESM/ocean-team

2023-02-01 18:49 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOS_LandGridComp.F90
> +    if (DO_FIRE_DANGER /= 0) then
I do not favor such integer criteria. Instead recommend logical `.true.` or `.false.`

2023-02-01 18:50 UTC, gmao-rreichle commented
Based on a brief inspection of the changes this looks ok to me from the land perspective.  
To be safe, @biljanaorescanin should run the standard GEOSldas tests before the @GEOS-ESM/land-team approves.
(Also needs updating to the latest develop branch.)

2023-02-01 19:25 UTC, adarmenov commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSland_GridComp/GEOS_LandGridComp.F90
> +    if (DO_FIRE_DANGER /= 0) then
Addressed with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/699/commits/df4695f0b650d240deb95292a96bed12a0267e27

2023-02-01 19:25 UTC, zhaobin74 approved these changes
Not related to landice. Approve.

2023-02-01 19:32 UTC, adarmenov commented
> ... (Also needs updating to the latest develop branch.)

@gmao-rreichle Addressed with  https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/699/commits/04821aa33a372867eaf9dca8e2e32a3df4f3cbe0

2023-02-01 20:46 UTC, tclune approved these changes
Please note that CMake provides a mechanism to register tests, and thereby make it easier for us to incorporate them into CI testing.   It would also avoid hardcoding the compiler (gfortran in this case)

 If at all interested please contact @mathomp4 or myself.

2023-02-01 20:54 UTC, sanAkel approved these changes

2023-02-01 20:55 UTC, sanAkel commented
> Please note that CMake provides a mechanism to register tests, and thereby make it easier for us to incorporate them into CI testing. It would also avoid hardcoding the compiler (gfortran in this case)
> 
> If at all interested please contact @mathomp4 or myself.

Yes, I'm interested and will reach out to @mathomp4. Thanks!

2023-02-02 13:18 UTC, biljanaorescanin approved these changes

2023-02-27 19:58 UTC, sdrabenh approved these changes

2023-02-27 19:58 UTC, merged