Add new 0.66 degree MOM6 grid into make_bcs
GEOS-ESM/GEOSgcm_GridComp pull request #712
Opened 2023-03-02 20:13 UTC by yvikhlya

and return back old 360x210 MOM6 grid in case someone wants to run it with old land.

2023-03-02 22:05 UTC, gmao-rreichle commented
Thanks, @yvikhlya.  Looks ok to me but...
1. @biljanaorescanin should test the revised make_bcs script just to make sure it works, if you haven't done this already
2. #707 also touches the make_bcs script by moving it into a subdir as part of the cleanup.  We need to be careful about merging the two PRs in the right order.
3. We are working on py versions of the make_bcs script, which are already on the develop branch and will need to be updated with the changes in the present PR.  @weiyuan-jiang will need to take care of this. 

Once item 1. is addressed, I'm happy to approve the PR.  We'll then need to work with @sdrabenh to merge #707 and the present PR in the correct order (item 2.).   We don't have to wait for item 3 since the py versions aren't ready for prime time anyway, but we have to remember to make the changes sooner rather than later.

2023-03-03 14:44 UTC, sanAkel commented
@yvikhlya Will either add **your** river routing **patch** script to _this_ PR or provide a link to it (by posting it elsewhere)?

Once you do it, I'll take the `DNA` label off- because without, nobody can reproduce the set up.

Thanks!

2023-03-03 15:49 UTC, yvikhlya commented
I use this script
https://github.com/GEOS-ESM/GEOS_Util/blob/main/coupled_diagnostics/g5lib/src/reroute_runoff/reroute.py
to fix runoff, but I would strongly discourage to take it as any sort of fix to runoff problem, but rather as "do not use it again" hack to let us proceed with our tests asap. We still have to fix runoff issue a proper way (which is independent from this PR issue).

2023-03-03 19:00 UTC, sanAkel commented
> I use this script https://github.com/GEOS-ESM/GEOS_Util/blob/main/coupled_diagnostics/g5lib/src/reroute_runoff/reroute.py to fix runoff, but I would strongly discourage to take it as any sort of fix to runoff problem, but rather as "do not use it again" hack to let us proceed with our tests asap. We still have to fix runoff issue a proper way (which is independent from this PR issue).

Thank you @yvikhlya

And for the _record_ the
> We still have to fix runoff issue a proper way (which is independent from this PR issue).

is: https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/681

2023-03-06 13:29 UTC, biljanaorescanin commented
@gmao-rreichle I've tested both options (T3MOM6 and T2MOM6) and they will produce whole set of boundary conditions. I presume science was tested by @sanAkel  and @yvikhlya  and resulting boundary conditions are what they expect to get.

2023-03-06 13:40 UTC, sanAkel commented
> @gmao-rreichle I've tested both options (T3MOM6 and T2MOM6) and they will produce whole set of boundary conditions. I presume science was tested by @sanAkel  and @yvikhlya  and resulting boundary conditions are what they expect to get. 


No! I haven't yet tested.

@sdrabenh,

2023-03-06 13:56 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T2MOM6 --  Med-Resolution  Tripolar 1   deg${CR} (MOM6-Tripolar-Ocean:   360x210 )"
2 comments:
1. Since `360x210` version does not work with currently supported `default land bcs` [NL3](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/077bb4d126a7cdda37598cd8eafb4cfacc1d1523/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs#L92-L93), this option should be **removed**. If any `user` wants to generate such, that user can clone an _older_ version (tag/branch) and help themselves. As such that version never worked and hence there should be no expectation of any _support_ ➡️ hence delete here.
2.

2023-03-06 14:03 UTC, sanAkel requested changes

2023-03-06 14:03 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T3MOM6 --  High-Resolution Tripolar 1/2 deg${CR} (MOM6-Tripolar-Ocean:   580x458 )"
This: `High-Resolution Tripolar 1/2 deg${CR}` is misleading since `T4MOM6 -- High-Resolution Tripolar` is also labeled **high** resolution.

1. The keyword **high** should be removed whereever it appears.
2. I suggest every option should say following:

```
${C2}TnnMOM6 -- Tripolar ${CR} (MOM6-Tripolar-Ocean: nxxny )"
```

where `nn = 1, 2, 3` for `T1MOM6, T2MOM6, T3MOM6` respectively; `T2MOM6` is for nx=580, ny=458.

2023-03-06 14:03 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
>            $orslv != 'T2MOM6' & \
remove `T2MOM6`.

2023-03-06 14:12 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T3MOM6 --  High-Resolution Tripolar 1/2 deg${CR} (MOM6-Tripolar-Ocean:   580x458 )"
I agree with @sanAkel's suggestion.  If I understand correctly, we would just delete "High-Resolution", "Low-Resolution", and "Med-Resolution" and delete the approximate resolution strings "1/2 deg", "1/4 deg", etc.   The nx by nx numbers speak for themselves.  If the approximate resolution strings are helpful, we could add "~", as in "~1/2 deg", "~1/4 deg", etc.,  instead of deleting these strings.

2023-03-06 14:41 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T3MOM6 --  High-Resolution Tripolar 1/2 deg${CR} (MOM6-Tripolar-Ocean:   580x458 )"
@gmao-rreichle I also think those _numbers_ (nx, ny) speak for themselves, hence no need for more verbiage. Such _informative_ language can go into our [wiki pages](https://github.com/GEOS-ESM/GEOSgcm/wiki/Instructions-for-the-Coupled-Model).

2023-03-06 15:51 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T2MOM6 --  Med-Resolution  Tripolar 1   deg${CR} (MOM6-Tripolar-Ocean:   360x210 )"
I was not sure what to do with 360x210 set up. It was commented, but not removed from make_bcs. It better be either commented or removed completely. If nobody has objections against removing it in next few hours, I'll do this.

2023-03-06 15:54 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T2MOM6 --  Med-Resolution  Tripolar 1   deg${CR} (MOM6-Tripolar-Ocean:   360x210 )"
Please **remove**.

2023-03-06 15:55 UTC, sdrabenh commented
Note, this PR is showing runtime failures with CircleCi. Has this PR been run or could this be an automated test issue?

2023-03-06 15:57 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
> https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/712#issuecomment-1456395492

@sdrabenh, I suspect reason for failure(s) is that it cannot read there new files. Right @mathomp4 ?

2023-03-06 15:58 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
Now, I intend to check it all myself. I have _queued_ it, but have no ETA when I'll get to it.

2023-03-06 16:00 UTC, sdrabenh commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
> 

@sanAkel sorry just saw your comment. That is what I suspect

2023-03-06 16:00 UTC, gmao-rreichle commented
@sdrabenh: This PR only touches the "make_bcs" script, which isn't exercised in any of the CircleCI tests.  Also, keep in mind that this PR will need updating after you merge #707, which moves "make_bcs" into a new location.

2023-03-06 16:08 UTC, biljanaorescanin commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
Boundary Conditions package would have failed @sanAkel if files weren't there. 
So files were at location when I was running and are still there.

2023-03-06 16:13 UTC, mathomp4 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
@sanAkel @sdrabenh I don't think it's that. It's dying *in run* so it gets through the scripting.

My first guess is that the CI does a `checkout-if-exists` step and so it's not just picking up this branch but also the `yv/feature/mom6-0.66deg` in GEOS_OceanGridComp as seen in https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/21

That PR from @yvikhlya is based on `develop` in the Ocean GC repo and in there line 653 (which is where the model is dying) is crapping out on:

```fortran
       call MAPL_GetPointer(EXPORT, T_Freeze_e, 'T_Freeze', _RC)
```

If that line requires, say, a new mom6 tag or something, it's possible the CI is just "unhappy" until the latest Ocean/MOM6 combo is brought into GEOSgcm fixture itself.

So this might be a case of we have to superpower merge it in because of CI issues.

2023-03-06 16:16 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
Thanks @mathomp4 I don't want to overload myself with `https://github.com/GEOS-ESM/GEOS_OceanGridComp/` making a fixture. If you have the bandwidth and want to do most driving, I can tack on. But let's not make a Friday of a Monday!

2023-03-06 16:22 UTC, mathomp4 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
@sanAkel It's just really a consequence of the CI scripting trying to be smart. This seems "safe" to pull in because, as @gmao-rreichle says below, it's touching a script my CI does not care about. But the `yv/feature/mom6-0.66deg` branch in Ocean GC doesn't quite run without some change elsewhere. 

If you, @sdrabenh, @biljanaorescanin, and @gmao-rreichle are fine with this, I can power it in with admin powers.

2023-03-06 16:37 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
> But the yv/feature/mom6-0.66deg branch in Ocean GC doesn't quite run without some change elsewhere.

It touches only several configs. How can this affect the build?

2023-03-06 16:39 UTC, sdrabenh commented
Thanks @mathomp4 . If @gmao-rreichle @biljanaorescanin @sanAkel @yvikhlya are fine with this PR, I have no objection to @mathomp4 powering it through.

2023-03-06 16:39 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
> If you, @sdrabenh, @biljanaorescanin, and @gmao-rreichle are fine with this, I can power it in with admin powers.

I'm generally ok with the changes but we MUST coordinate this PR with #707.  At this moment, #707 is ready, and I assume @sdrabenh will merge it first.  Then we have to modify this PR in response.  So please refrain from using superpowers unless we have this sorted, so we're not inadvertently merging a conflicting set of PRs.

2023-03-06 16:42 UTC, yvikhlya commented
```
ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210

....

call MAPL_GetPointer(EXPORT, T_Freeze_e, 'T_Freeze', _RC)
```

None of the above was introduced by `yv/feature/mom6-0.66deg` PRs.

2023-03-06 16:43 UTC, yvikhlya commented
> Thanks @mathomp4 . If @gmao-rreichle @biljanaorescanin @sanAkel @yvikhlya are fine with this PR, I have no objection to @mathomp4 powering it through.

Still need to do 360x210 clean up. Wait for one more commit please.

2023-03-06 16:44 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
I go with @gmao-rreichle - his word be bye final one!

2023-03-06 16:47 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +ln -s $MAKE_BCS_INPUT_DIR/ocean/MOM6/360x210 data/MOM6/360x210
> > If you, @sdrabenh, @biljanaorescanin, and @gmao-rreichle are fine with this, I can power it in with admin powers.
> 
> 
> 
> I'm generally ok with the changes but we MUST coordinate this PR with #707.  At this moment, #707 is ready, and I assume @sdrabenh will merge it first.  Then we have to modify this PR in response.  So please refrain from using superpowers unless we have this sorted, so we're not inadvertently merging a conflicting set of PRs.

@gmao-rreichle Please put a DNA label

2023-03-06 17:23 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T2MOM6 --  Med-Resolution  Tripolar 1   deg${CR} (MOM6-Tripolar-Ocean:   360x210 )"
Addressed with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/712/commits/aee586c15dadea72e25b67fd3519d60867ebcb9b

2023-03-06 17:23 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
> +   echo "   ${C2}T3MOM6 --  High-Resolution Tripolar 1/2 deg${CR} (MOM6-Tripolar-Ocean:   580x458 )"
Addressed with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/712/commits/aee586c15dadea72e25b67fd3519d60867ebcb9b

2023-03-06 17:25 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/make_bcs
>            $orslv != 'T2MOM6' & \
Addressed with https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/712/commits/aee586c15dadea72e25b67fd3519d60867ebcb9b

2023-03-06 19:40 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/makebcs/make_bcs
> +set  MOM_VERSION = UNDEF
I changed this initialization.  Seems safer to me to assume nothing, and let the subsequent if block take care of setting the version.  @yvikhlya, please double-check to make sure I didn't ruin anything.

2023-03-06 19:48 UTC, gmao-rreichle commented
@yvikhlya, @biljanaorescanin, @sdrabenh, @mathomp4:
I merged develop into Yury's branch through a command-line merge.  This didn't even require explicitly resolving any conflicts.  Git was apparently smart enough to recognize that we used "git mv" on "make_bcs" in our reorganization (#707) and then simply moved Yury's modified "make_bcs" into the new "./makebcs" subdir.  Not sure why the merge on git**hub** indicated a conflict and complained about write permission for Biljana.  
I added one more commit with some cleanup, see inline comment above.
This is now ok with me, and I'm happy for Matt to super-approve.
cc: @sanAkel

2023-03-06 19:54 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/makebcs/make_bcs
> +set  MOM_VERSION = UNDEF
This looks fine to me.

2023-03-06 20:17 UTC, mathomp4 approved these changes
Re-approve

2023-03-06 20:43 UTC, merged

2023-03-07 02:04 UTC, sanAkel commented
FYI: @danholdaway, @Dooruk