Merge GEOS/mitgcm
GEOS-ESM/GEOSgcm_GridComp pull request #724
Opened 2023-03-11 15:31 UTC by sdrabenh

2023-03-13 14:35 UTC, amolod requested changes
Nothing in moist should be retained from the branch. all as you have it in the new develop. cicethermo changes and the rest we need.

2023-03-14 22:35 UTC, amolod commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/aer_cloud.F90
Please leave this file as in develop

2023-03-14 22:35 UTC, amolod commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/data_txt
Please leave this file as in develop

2023-03-14 22:36 UTC, amolod commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/ras.F90
Please leave this file as in develop

2023-03-14 22:38 UTC, amolod requested changes
Please leave all moist gridcomp files as in develop

2023-03-15 14:01 UTC, mathomp4 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/Raster/makebcs/mkMITAquaRaster.F90
> +   OPEN(UNIT=iUnit, name='data.exch2', form='formatted', status='old')
This is the reason the GNU build in CI is failing.

2023-03-16 01:05 UTC, sanAkel commented
Adding `DNA` because [this problem](https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/23#issuecomment-1470065965)

2023-03-16 21:37 UTC, amolod commented
@mathomp4 , @sanAkel, i have checked in an update to mitraster to let it compile. as for the other requests i made above (moist from develop, not from the branch), i am not sure how to check or even do this myself. but the ocean grid comp should be ready to go and the dependency removed.

2023-03-16 21:51 UTC, sanAkel commented
> @mathomp4 , @sanAkel, i have checked in an update to mitraster to let it compile. as for the other requests i made above (moist from develop, not from the branch), i am not sure how to check or even do this myself. but the ocean grid comp should be ready to go and the dependency removed.

Okay @amolod 
,

2023-03-20 22:07 UTC, amolod commented
@sanAkel santha this is working for @yvikhlya  (he told me on friday), so i think we are all set. all is ready for the merge. would you do this please?

2023-03-20 22:17 UTC, sanAkel commented
> @sanAkel santha this is working for @yvikhlya  (he told me on friday), so i think we are all set. all is ready for the merge. would you do this please?

@amolod,
If @yvikhlya says it works for him, we can proceed.

As for any merge in _this_ that's up to @sdrabenh or @wmputman.

2023-03-21 15:27 UTC, sdrabenh commented
> 

@sanAkel @amolod @yvikhlya it looks as though these 3 PRs ready to be undrafted:
[GEOSgcm_GridComp #724](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/724) (this one)
[GEOSgcm_App #423](https://github.com/GEOS-ESM/GEOSgcm_App/pull/423)
[GEOS_OceanGridComp #23](https://github.com/GEOS-ESM/GEOS_OceanGridComp/pull/23)
If so, shall I undraft them?

2023-03-21 15:27 UTC, yvikhlya commented
> If @yvikhlya says it works for him, we can proceed.

Can't confirm this yet.

2023-03-21 15:56 UTC, mathomp4 commented
@sdrabenh I'm working on identifying the gcm_setup issue hitting the CI.

2023-03-21 22:17 UTC, zhaobin74 requested changes
@atrayano @amolod, after the load balancing was implemented for CICEthermo, all exports of ```CICE4ColumnPhys``` grid comp must  go through the relevant buffers in a bunch of *.h files. I don't see  those files are changed. 

Please see comments @HamidehGMAO put in CICE4ColumnPhys [link](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/bf5b0af2424e976050d679c4bdf69a29c10dfaf8/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90#L2196) 

You could also ```grep FCONDBOTN *.h``` in GEOSsaltwaterGridComp/  to see an example.

2023-03-22 03:13 UTC, weiyuan-jiang commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py
I think we should use  remap_lake_landice_saltwater.py and remap_catchANDcn.py

2023-03-22 13:36 UTC, yvikhlya commented
It builds, but it does not produce correct coupled setup.

2023-03-22 14:19 UTC, mathomp4 commented
> It builds, but it does not produce correct coupled setup.

You are the expert. 😄 

I can say that all four change (UMD, App, GCM, and Ocean) seem to be zero-diff for AMIP in any order. I can also run MOM6 with all four in any order as well, though all I test is "does it run", not "does it run and make good science"!

2023-03-22 16:36 UTC, amolod submitted a review, later dismissed

2023-03-22 16:51 UTC, gmao-rreichle commented
@sdrabenh, the branch still includes
GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py
Unless this file is removed from the branch, I disagree with merging the branch.

2023-03-22 18:14 UTC, amolod commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py
@sdrabenh is it ok to remove this file?

2023-03-22 18:46 UTC, amolod commented
> @sdrabenh, the branch still includes GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py Unless this file is removed from the branch, I disagree with merging the branch.

@sdrabenh are you ok removing this file?

2023-03-22 19:02 UTC, sdrabenh commented
> > @sdrabenh, the branch still includes GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py Unless this file is removed from the branch, I disagree with merging the branch.
> 
> @sdrabenh are you ok removing this file?

Yes. I agree with @gmao-rreichle . This is not needed.

2023-03-22 19:20 UTC, amolod commented
> > > @sdrabenh, the branch still includes GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py Unless this file is removed from the branch, I disagree with merging the branch.
> > 
> > 
> > @sdrabenh are you ok removing this file?
> 
> Yes. I agree with @gmao-rreichle . This is not needed.

it was removed.

2023-03-22 19:31 UTC, gmao-rreichle commented
> it was removed.

Thanks, @amolod  and @sdrabenh.  It's fine with me, then.

2023-04-04 19:41 UTC, amolod commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts/regrid_sfc_rst.py
it was removed

2023-05-10 14:14 UTC, gmao-rreichle approved these changes

2023-05-16 17:47 UTC, mathomp4 approved these changes

2023-05-16 18:52 UTC, mathomp4 commented
The CI is showing a failure in CICE4 when running coupled debug with GNU:

```
At line 3225 of file /root/project/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_CICE4ColumnPhysGridComp.F90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'deltavol1' (1/820)
```

I'm going to try and duplicate on discover. I'll contact @zhaobin74 and maybe @atrayano to figure out the issue. Hopefully quickly.

2023-05-17 11:29 UTC, mathomp4 approved these changes
Re approve after my GNU fix

2023-05-17 11:30 UTC, mathomp4 commented
Could someone from @GEOS-ESM/ocean-team re-approve this for @sdrabenh? All previous reviews were dismissed when I implemented my fix for GNU

2023-05-17 14:41 UTC, sanAkel commented
> Could someone from @GEOS-ESM/ocean-team re-approve this for @sdrabenh? All previous reviews were dismissed when I implemented my fix for GNU

@yvikhlya, I believe you tested this [PR](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/724#discussion_r1157685527) If so, can you please look into @mathomp4's ⬆️ request. Thanks!

2023-05-17 14:42 UTC, mathomp4 approved these changes

2023-05-17 14:43 UTC, merged