add new sea ice components for coupling to CICE6
GEOS-ESM/GEOSgcm_GridComp pull request #772
Opened 2023-06-20 17:54 UTC by zhaobin74

This PR adds two new gridded comps to support coupling `GEOS` to `CICE6` sea ice model from [CICE Consortium](https://github.com/CICE-Consortium).  

`GEOS_SeaiceInterfaceGridComp` and `CICE_GEOSPlug` were introduced to allow `GEOS` atmosphere/surface to thermally couple to CICE6 in a semi-implicit manner while conserving energy and mass.

`USE_CICE_Thermo = 2` switch is used to turn on the new `GEOS_SeaiceInterfaceGridComp` and use `CICE6` sea ice model.
Currently `USE_CICE_Thermo = 0` is for AMIP `Dataseaice` and `USE_CICE_Thermo = 1` for coupled `CICE4` sea ice model.

Testing is done in 3 configurations:
- AMIP style run, 2-days segment, `c12xo1` resolution,  **zero-diff results**
- Coupled run with MOM5, 2 days segment, `c90-360x200` resolution, **zero-diff results**
- Coupled run with MOM6, 2 days segment, `c12-72x36` resolution, **zero-diff results**    

**NOTE: CICE6 coupling is still in EXPERIMENTAL stage** 
 
This PR depends on  https://github.com/GEOS-ESM/GEOSgcm_App/pull/478 and https://github.com/GEOS-ESM/GEOSgcm/pull/611

2023-06-20 19:26 UTC, gmao-rreichle approved these changes
Nothing really touches the land, so trivially good for the land group.
However, I'm wondering how the cice6 "restart" code here:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/zhaobin74/cice6coupled/GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/cice6_app/restart
fits with the other GEOS restart tools here:
https://github.com/GEOS-ESM/GEOS_Util/tree/main/pre/remap_restart
and here:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/develop/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts
This may require more thought now or at a later time. 
cc: @biljanaorescanin @weiyuan-jiang

2023-06-20 19:36 UTC, tclune submitted a review, later dismissed
CMake changes ok.

2023-06-20 19:48 UTC, zhaobin74 commented
> Nothing really touches the land, so trivially good for the land group. However, I'm wondering how the cice6 "restart" code here: https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/zhaobin74/cice6coupled/GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/cice6_app/restart fits with the other GEOS restart tools here: https://github.com/GEOS-ESM/GEOS_Util/tree/main/pre/remap_restart and here: https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/develop/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/Utils/mk_restarts This may require more thought now or at a later time. cc: @biljanaorescanin @weiyuan-jiang

Good point, @gmao-rreichle. 

The tools in `cice6_app/restart` are to generate restart files for `GEOS_SeaiceInterfaceGridComp` (its import and internal) so the relevant states have proper initial values. They could be bootstrapped but will be a big shock to the model. Once these restarts are available, they can be remapped using https://github.com/GEOS-ESM/GEOS_Util/tree/main/pre/remap_restart. Right now I put these tools alongside with cice6 as they are specific to running with CICE6. They may move to another location when `GEOS_SeaiceInterfaceGridComp` goes main stream.
         
Thanks.

2023-06-21 15:37 UTC, yvikhlya submitted a review, later dismissed

2023-07-24 20:20 UTC, sanAkel commented on GEOS_GcmGridComp.F90
> +                         'TI     ','SI     ' ,                      &
I like this! 👍

2023-07-24 20:23 UTC, sanAkel commented on GEOS_GcmGridComp.F90
> +   !========CICE CALLBACK RELATED======
@tclune, @atrayano, Since the GCM GC is going to get this (call back) block, and given the desire to have an explicit coupler (in future), please think of a way to wrap this up in to a subroutine or something for later.

2023-07-24 20:29 UTC, tclune commented on GEOS_GcmGridComp.F90
> +   !========CICE CALLBACK RELATED======
@sanAkel   Could you expand a bit?     Your request is a bit terse to understand.

2023-07-24 20:32 UTC, sanAkel commented on GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/cice6_cmake/CMakeLists.txt
> +#
@zhaobin74, Following 3 commented lines can be deleted?

2023-07-24 20:33 UTC, sanAkel requested changes
See comments. Minor changes requested.

2023-07-24 20:43 UTC, zhaobin74 commented on GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/cice6_cmake/CMakeLists.txt
> +#
will do, thanks.

2023-07-24 21:31 UTC, zhaobin74 commented on GEOSogcm_GridComp/GEOSseaice_GridComp/CICE_GEOSPlug/cice6_cmake/CMakeLists.txt
> +#
Done!

2023-07-25 13:13 UTC, zhaobin74 commented
> 

fixed by https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/772/commits/daf7748456b4601fcbbe34a4e408683f849dd0e5

2023-07-25 13:14 UTC, zhaobin74 commented
> See comments. Minor changes requested.
Fixed by https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/772/commits/daf7748456b4601fcbbe34a4e408683f849dd0e5. Thanks.

2023-07-25 15:37 UTC, gmao-rreichle approved these changes

2023-07-27 19:57 UTC, sdrabenh approved these changes

2023-07-27 20:00 UTC, mathomp4 approved these changes
re-approve

2023-07-27 20:00 UTC, merged