Feature/v11 datm
GEOS-ESM/GEOSgcm_GridComp pull request #799
Opened 2023-08-14 18:46 UTC by mfmehari

Atanas’ Data Atm - feature/atrayano/dataatm has been updated, and a few bugs have been fixed.
It replaces the old GEOS_DataAtmGridComp.F90 with a new one.
It is a zero diff PR.

2023-08-14 19:36 UTC, tclune approved these changes
cmake ok

2023-08-15 11:59 UTC, mathomp4 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (DO_DATAATM) then
```suggestion
    if (DO_DATAATM /= 0) then
```

Since `DO_DATAATM` is an `integer`, we need to use an integer comparison here (as is done above)

2023-08-15 11:59 UTC, mathomp4 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (DO_DATAATM) then
@mfmehari Can you confirm this is the right thing to do (I assume so given code above it). If so, we can commit the suggestion.

2023-08-15 15:07 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (DO_DATAATM) then
> @mfmehari Can you confirm this is the right thing to do (I assume so given code above it). If so, we can commit the suggestion.

@mathomp4  Yes, it should be an integer comparison. Thank you for the correction.

2023-08-16 12:39 UTC, mathomp4 approved these changes
Re-approve for CMake.

2023-08-16 15:10 UTC, sanAkel requested changes

2023-08-16 15:10 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +#define DEBUG_DATAATM
What is the purpose of `DEBUG_DATAATM`?

2023-08-16 15:29 UTC, mfmehari commented on GEOS_GcmGridComp.F90
@sanAkel Done.

2023-08-16 15:34 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +#define DEBUG_DATAATM
@sanAkel I will check with Atanas on this.

2023-08-16 15:44 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (associated(SURF_INTERNAL_STATE%RoutingType) .or. DO_DATAATM /=0) then ! routing file exists or we run DataAtm
@sanAkel These two comment lines were done by someone else.

2023-08-16 15:48 UTC, yvikhlya commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (associated(SURF_INTERNAL_STATE%RoutingType) .or. DO_DATAATM /=0) then ! routing file exists or we run DataAtm
> @sanAkel These two comment lines were done by someone else.

!ALT means Atanas. You can ask him to remove these comments or just delete them.

2023-08-16 16:18 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (associated(SURF_INTERNAL_STATE%RoutingType) .or. DO_DATAATM /=0) then ! routing file exists or we run DataAtm
@yvikhlya good to know, thanks.

2023-08-16 16:35 UTC, sanAkel requested changes

2023-08-16 16:35 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +#define DEBUG_DATAATM
👍 Please do not leave code that you added for debugging!

2023-08-16 18:51 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +#define DEBUG_DATAATM
Okay, thanks.

2023-08-16 19:28 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    if (associated(SURF_INTERNAL_STATE%RoutingType) .or. DO_DATAATM /=0) then ! routing file exists or we run DataAtm
@sanAkel commented lines removed.

2023-08-16 19:32 UTC, mfmehari commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +#define DEBUG_DATAATM
DEBUG_DATAATM removed.

2023-08-16 22:52 UTC, sanAkel submitted a review, later dismissed

2023-08-20 09:50 UTC, gmao-rreichle commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +  integer :: DO_DATAATM
If I understand "DATAATM" correctly, it's an ocean-only model config.  That is, the ocean model is running "offline", without the atmospheric or land models.  (For the land, the equivalent functionality is the GEOSldas App.)  
For land-centric developers and users, "DATAATM" is a bit  confusing, because "DATAATM" could also mean an off-line land model run.  The fact that "DATAATM" is intended for the ocean only is not obvious from the rc variable name.  Could the name be made clearer?  Maybe something like "DATAATM4OCEAN"?

2023-08-22 16:03 UTC, sdrabenh commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +  integer :: DO_DATAATM
@mfmehari this is a valid point from the land model perspective. Could you clarify your rc variable name?

2023-08-23 14:57 UTC, wmputman commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +  integer :: DO_DATAATM
@gmao-rreichle do you have a resource parameter you need to running the offline land model?

Can we use: DO_DATA_ATM4OCN

2023-08-23 20:35 UTC, sdrabenh approved these changes

2023-08-23 20:40 UTC, gmao-rreichle approved these changes

2023-08-23 20:49 UTC, bena-nasa approved these changes

2023-08-23 20:53 UTC, amolod approved these changes

2023-08-23 21:06 UTC, yvikhlya approved these changes

2023-08-23 21:12 UTC, merged