Feature/mfmehari/krok obio
GEOS-ESM/GEOSgcm_GridComp pull request #871
Opened 2023-12-13 16:44 UTC by mfmehari

OBIO (NOBM) is integrated into the Krok Model. 
It is still in testing phase.
It is a zero diff PR.

2023-12-13 17:39 UTC, sanAkel commented
Thanks @mfmehari I'll take a look at this tomorrow (late in the day).

Can you list all the ways you tested this PR. Example coupled ( which ocean, what resolution(s)), also you must do an uncoupled model run - it should preserve answers in both (uncoupled and coupled) modes- this is needed because you have changed source code at a lot of places.

2023-12-13 17:46 UTC, tclune approved these changes
cmake changes ok

2023-12-13 19:59 UTC, mfmehari commented
> Thanks @mfmehari I'll take a look at this tomorrow (late in the day).
> 
> Can you list all the ways you tested this PR. Example coupled ( which ocean, what resolution(s)), also you must do an uncoupled model run - it should preserve answers in both (uncoupled and coupled) modes- this is needed because you have changed source code at a lot of places.

@sanAkel 
It is tested with the coupled model run:
AGCM: C12 (IM:12 x JM:72) and LM:72
OGCM:  IM:72 x JM:36 and LM:50
Okay, I will do the uncoupled run.
Thank you!

2023-12-14 15:55 UTC, mfmehari commented
> > Thanks @mfmehari I'll take a look at this tomorrow (late in the day).
> > Can you list all the ways you tested this PR. Example coupled ( which ocean, what resolution(s)), also you must do an uncoupled model run - it should preserve answers in both (uncoupled and coupled) modes- this is needed because you have changed source code at a lot of places.
> 
> @sanAkel It is tested with the coupled model run: AGCM: C12 (IM:12 x JM:72) and LM:72 OGCM (MOM6): IM:72 x JM:36 and LM:50 Okay, I will do the uncoupled run. Thank you!

2023-12-14 16:00 UTC, mfmehari commented
> > Thanks @mfmehari I'll take a look at this tomorrow (late in the day).
> > Can you list all the ways you tested this PR. Example coupled ( which ocean, what resolution(s)), also you must do an uncoupled model run - it should preserve answers in both (uncoupled and coupled) modes- this is needed because you have changed source code at a lot of places.
> 
> @sanAkel It is tested with the coupled model run: AGCM: C12 (IM:12 x JM:72) and LM:72 OGCM (MOM6): IM:72 x JM:36 and LM:50 Okay, I will do the uncoupled run. Thank you!

@sanAkel Hi Santha, 
Tested the uncoupled run and it has a zero diff.
AGCM: C12 (im:12 x JM:72) and LM:72
Data_Ocean Horizontal Resolution code: o1 (1  -deg,  360x180  Reynolds)
Thank you!

2023-12-20 12:23 UTC, sanAkel commented
@mfmehari Please update when you have:

1. Added and,
2. Tested a `2d mask` export from MOM5 _plug_. 

Because ⬆️ needs to happen in [Ocean GC repository](https://github.com/GEOS-ESM/GEOS_OceanGridComp), adding a contingency.

Once you have above 1 and 2 done, please remove this contingency. Thanks!

2024-01-24 17:25 UTC, sdrabenh approved these changes

2024-01-24 17:55 UTC, bena-nasa approved these changes

2024-02-07 21:29 UTC, sdrabenh approved these changes

2024-02-07 22:30 UTC, gmao-rreichle approved these changes
Changes ok from Land perspective.  Would appreciate a more descriptive PR title.

2024-02-08 00:57 UTC, sanAkel commented on GEOS_GcmGridComp.F90
> +    call MAPL_GetResource ( MAPL, DO_DATA_ATM4OCN,  Label="USE_DATA_ATM4OCN:", DEFAULT=0, _RC)
Logical (`True` or `False`) are preferred than int for `DO_DATA_ATM4OCN`

2024-02-08 00:59 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOS_SurfaceGridComp.F90
> +    call MAPL_GetResource ( MAPL, DO_DATA_ATM4OCN, Label="USE_DATA_ATM4OCN:" , DEFAULT=0, RC=STATUS)
See ⬆️ comment reg preference for logicals

2024-02-08 01:01 UTC, sanAkel commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSsurface_GridComp/GEOSsaltwater_GridComp/GEOS_SaltWaterGridComp.F90
> +    call MAPL_GetResource ( MAPL, DO_DATA_ATM4OCN,  Label="USE_DATA_ATM4OCN:" ,   DEFAULT=0, _RC)
Logical `DO_DATA_ATM4OCN` is preferred

2024-02-08 01:01 UTC, sanAkel commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +    call MAPL_GetResource ( MAPL, DO_DATA_ATM4OCN, Label="USE_DATA_ATM4OCN:" ,  DEFAULT=0,     __RC__ )
Across the board logicals please

2024-02-08 01:02 UTC, sanAkel requested changes
@mfmehari Please consider making suggested changes.

2024-02-08 14:13 UTC, lcandre2 approved these changes

2024-02-08 16:27 UTC, mathomp4 commented
> @mfmehari Please consider making suggested changes.

@sanAkel I guess the only issue is that the rest of the `DO_` resources in the gridcomp around there do not use logicals. 
```
    call MAPL_GetResource ( MAPL, DO_OBIO, Label="USE_OCEANOBIOGEOCHEM:", DEFAULT=0, _RC)
    call MAPL_GetResource ( MAPL, DO_DATASEA, Label="USE_DATASEA:", DEFAULT=1, _RC)
    call MAPL_GetResource ( MAPL, DO_WAVES, Label="USE_WAVES:", DEFAULT=0, _RC)
    call MAPL_GetResource ( MAPL, DO_SEA_SPRAY, Label="USE_SEA_SPRAY:", DEFAULT=0, _RC)
```

I mean, it's what they *should* do but... I guess the question is should we be consistent?

2024-02-08 16:47 UTC, sanAkel commented
> > @mfmehari Please consider making suggested changes.
> 
> @sanAkel I guess the only issue is that the rest of the `DO_` resources in the gridcomp around there do not use logicals.
> 
> ```
>     call MAPL_GetResource ( MAPL, DO_OBIO, Label="USE_OCEANOBIOGEOCHEM:", DEFAULT=0, _RC)
>     call MAPL_GetResource ( MAPL, DO_DATASEA, Label="USE_DATASEA:", DEFAULT=1, _RC)
>     call MAPL_GetResource ( MAPL, DO_WAVES, Label="USE_WAVES:", DEFAULT=0, _RC)
>     call MAPL_GetResource ( MAPL, DO_SEA_SPRAY, Label="USE_SEA_SPRAY:", DEFAULT=0, _RC)
> ```
> 
> I mean, it's what they _should_ do but... I guess the question is should we be consistent?

@mathomp4 (and @mfmehari), your ⬆️ question is a relevant one. Following are my _current_ thoughts.
1. [This PR](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/871) is to a repo that has decades of (...) built in. There is absolutely no way we can accomplish `should we be consistent?` **unless** one of _us_ spends _some time_ to _clean_ this (logical) aspect and indeed so many, many, ... others; ultimately we'll be looking at a rewrite! (Just look at surface GC .F90, look at its length and scope? Anyway let's leave it out _here_).
2. I suggestions to @mfmehari are to the point of `what they _should_ do` so things are _better_ going forward. I had the same comments earlier for the _waves_PR_ from @adarmenov and others before it; I'm being consistent in my suggestions.

@mathomp4 did I answer your question(s)?

2024-02-08 16:57 UTC, yvikhlya commented
I guess the issue with boolean options is that *.rc format does not support them and such options are read as integers, 0 or 1, and used as integers all over GEOSgcm.

2024-02-08 17:02 UTC, mfmehari commented
@sanAkel If we are okay with DO_DATA_ATM4OCN only being in logical form, I could go ahead change its type, thank you!

2024-02-08 17:34 UTC, sanAkel commented
> @sanAkel If we are okay with DO_DATA_ATM4OCN only being in logical form, I could go ahead change its type, thank you!

👍 Let's just try to do _good_ here on ...

2024-02-08 20:38 UTC, mfmehari commented on GEOSogcm_GridComp/GEOS_OgcmGridComp.F90
> +    call MAPL_GetResource ( MAPL, DO_DATA_ATM4OCN, Label="USE_DATA_ATM4OCN:" ,  DEFAULT=0,     __RC__ )
> Across the board logicals please

@sanAkel The type of DO_DATA_ATM4OCN has been changed from int to logical.

2024-02-08 20:39 UTC, mfmehari commented
@sanAkel The type of DO_DATA_ATM4OCN has been changed from int to logical.

2024-02-08 22:28 UTC, sanAkel approved these changes

2024-02-21 13:53 UTC, sdrabenh approved these changes

2024-02-21 13:57 UTC, mathomp4 approved these changes

2024-02-21 14:01 UTC, merged

2024-02-21 16:06 UTC, mfmehari commented
Thank you all! @sdrabenh @mathomp4 @sanAkel @tclune @bena-nasa @lcandre2 @gmao-rreichle