Dsl/moist/radiation coupling - RadCouple Port in pyMoist
GEOS-ESM/GEOSgcm_GridComp pull request #953
Opened 2024-06-13 19:35 UTC by mattweil11

Ticket [NDSL] Radiation Coupling #937 
do_qa not implemented in radiation_coupling.py
Waiting on up to date testing data
Tests fail for CLDREFFL (5.55%) and CLDREFFI (5.08%)
Max Error set at 1e-9

2024-06-13 19:53 UTC, FlorianDeconinck commented
0 diff explainer: this is related to the port of the Moist physics to the NDSL stack, it's execution and compilation is deactivated by default

2024-06-17 16:20 UTC, FlorianDeconinck requested changes

2024-06-17 16:20 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/constants.py
> +alhlbcp = MAPL_ALHL / MAPL_CP
ALL CAPS for global constants

Look through the code.

2024-06-17 16:20 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +#Calculate ice cloud effective radius [m]
Rename to `cloud_effective_radius_ice` and put a docstring to document the match to LDRADIUS4_X.

See docstrings standard: https://peps.python.org/pep-0257/

2024-06-17 16:20 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +def LDRADIUS4_ICE(
See above.

2024-06-17 16:20 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +def LDRADIUS4_LIQUID(
See above.

2024-06-17 16:20 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
>          if self.do_qa:
Move the `do_qa` handling in `__init__` and live a one liner comment here

2024-06-17 18:22 UTC, FlorianDeconinck approved these changes
Couple of minor things, then we can merge

2024-06-17 18:22 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +def RHO(
Rename air_density

2024-06-17 18:22 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +            raise NotImplementedError("Module procedures QSAT0 and QSAT3 that are needed for GEOS_QSAT are not implemented")
"[Radiation Coupling] Diagnostic (do_qa) not implemented. (GEOS_QSAT missing)"

2024-06-17 18:23 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +def RHO(
Unless `rho` is a common name for air_density I guess

2024-06-17 18:26 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
> +def RHO(
rho is common name for density in general. Will change to air_density to specify

2024-06-17 18:42 UTC, merged