[NDSL] Aer Activation #942
GEOS-ESM/GEOSgcm_GridComp pull request #964
Opened 2024-07-24 21:33 UTC by mattweil11

Port of Aer Activation component of Moist to pyMoist

Original code: [aer_actv_single_moment.F90:AerActivation](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/db55c301840d98b788b0e17045510af726c0f555/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/aer_actv_single_moment.F90#L39)

Parent: https://github.com/GEOS-ESM/SMT-Nebulae/issues/57

See state of validation at: https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/942

2024-07-25 12:14 UTC, FlorianDeconinck commented
`0 diff trivial`: DSL port work, no changes to current production code

2024-07-25 12:42 UTC, FlorianDeconinck requested changes
Careful about merging code that is destructive to previous work!

Please do a pass on the documentation for the types. Instead of just `xx (Float)` also indicated `In`/`Out`/`Inout`.

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def GammLn(xx: Float) -> Float:
Let's move this guy in a file `numerical_recipes`

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def _gser_stencil(a: Float, x: Float, gln: Float) -> Float:
Same as above. Maybe rename or is `gser` expected?

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +        # TODO; Allow print in GT4Py
`TODO:`

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def _gcf_matrix_stencil(a: Float, x: Float, gln: Float) -> Float:
Same as above

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def GammP(a: Float, x: Float) -> Float:
Same as above

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def Erf(x: Float) -> Float:
Same as above

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +    if x < 0.0e00:
`<0.0e00` isn't that `0.0` ?

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +        self.higher_dimensional_storages = stencil_factory.from_origin_domain(
rename that stencil

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/__init__.py
> +from .translate_aer_activation import TranslateAerActivation
This is wrong. `TranslateAerActivation` should be added nothing removed

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/translate_radiation_coupling.py
Do not remove

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
Do not remove

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/constants.py
Do not remove

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/get_data.sh
Do not replace. Make it additive to bring both data packet in a common `moist` subdirectory

2024-07-25 12:42 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/run_tests.sh
Do not replace. Make it additive to have both test runnable.

2024-07-25 14:18 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def _gser_stencil(a: Float, x: Float, gln: Float) -> Float:
gser is name of function in Fortran so I just kept it. I removed the _stencil portion as it is not a stencil.

2024-07-25 14:19 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +        # TODO; Allow print in GT4Py
Fixed, same with the TODO: in GammP

2024-07-25 14:19 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def _gcf_matrix_stencil(a: Float, x: Float, gln: Float) -> Float:
Got rid of the _stencil and renamed to gcf_matrix

2024-07-25 14:20 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def GammP(a: Float, x: Float) -> Float:
Added to numerical recipes along with the other functions that contained "numerical recipes" in the docstring

2024-07-25 14:20 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/translate_radiation_coupling.py
Added back

2024-07-25 14:20 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/radiation_coupling.py
Added back

2024-07-25 14:21 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/constants.py
Added back

2024-07-25 14:23 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/get_data.sh
Put everything back into pyMoist/tests_data/geos_11.5.2/moist, did not get data from radiation coupling on NCCS as port is for aer_activation

2024-07-25 14:24 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/run_tests.sh
Added back; user can get data for radiation coupling and change which_modules if desired

2024-07-25 14:24 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/aer_activation.py
> +def GammLn(xx: Float) -> Float:
Put into numerical_recipes

2024-07-25 19:27 UTC, mattweil11 commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/__init__.py
> +from .translate_aer_activation import TranslateAerActivation
TranslateRadCouple line added

2024-07-25 20:36 UTC, FlorianDeconinck requested changes
Clean up data wget so we can do AerActivation and RadCoupling at the same time

2024-07-25 20:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/get_data.sh
> +rm AerActivation_nc.tar.gz
Have the `get_data.sh` bring both data set into a single `moist` directory

2024-07-25 20:38 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/get_data.sh
> +rm AerActivation_nc.tar.gz
Also look at renaming your `higher_dimensional_storage` stencil to something closer to `aerosol_activation`

2024-07-29 12:36 UTC, FlorianDeconinck approved these changes

2024-07-29 12:39 UTC, merged