dsl/develop/redistribute_clouds
GEOS-ESM/GEOSgcm_GridComp pull request #977
Opened 2024-08-07 14:46 UTC by katrinafandrich

Ported and tested RedistributeClouds #958

2024-08-08 13:32 UTC, FlorianDeconinck commented
`0-diff trivial` because NDSL porting - no change to Fortran

2024-08-08 14:59 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/redistribute_clouds.py
> +        RAD_CF (FloatField): Radiation cloud fraction.
Let's follow a `NAME (DIM intent) for the documentation. E.g. `RAD_CF (3D inout)`

2024-08-08 15:00 UTC, FlorianDeconinck requested changes
Please merge `dsl/develop` back in (either via the Github interface or by hand)
Please run `pre-commit run --all-files` at the root of pyMoist which will apply the code guidelines

2024-08-08 15:26 UTC, pchakraborty commented
@FlorianDeconinck Do we need to continue running the build tests?

If not, @mathomp4 is it possible to somehow turn off the build tests for PR into `dsl/develop`. One possible way might be to remove `.circleci/config.yaml` in the branch `dsl/develop`, but that might be too much.

2024-08-15 15:28 UTC, FlorianDeconinck approved these changes
LGTM

2024-08-15 15:29 UTC, merged

2024-08-15 17:40 UTC, FlorianDeconinck commented
> @FlorianDeconinck Do we need to continue running the build tests?
> 
> If not, @mathomp4 is it possible to somehow turn off the build tests for PR into `dsl/develop`. One possible way might be to remove `.circleci/config.yaml` in the branch `dsl/develop`, but that might be too much.

@pchakraborty / @mathomp4 : the CI clean up work has been done. No more build CI for any `dsl/*` branch * custom github action for PR to `dsl/develop` to trigger our `pre-commit` run for the python