[NDSL] UW Convection port
GEOS-ESM/GEOSgcm_GridComp pull request #993
Opened 2024-09-10 15:24 UTC by katrinafandrich

UW Shallow Water Convection physics port - from the Moist component.

This ports is aimed at the core numerics, e.g.: [uwshcu.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/v2.5.2/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/uwshcu.F90)

Version ported: [v2.5.2](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/v2.5.2) (as part of GEOS v11..5.2)

2024-09-10 17:22 UTC, FlorianDeconinck requested changes
To be merged after QSat #994 

- [x] Resolve merge conflict in `.gitignore`
- [x] Merge `dsl/develop` and resolve conflicts
- [ ] Run lint with `pre-commit run --all-files`
- [x] Move the files in a UW directory and drop a README.md describing what's ported, what's missing and any additional notes (with date)
- [ ] Revert changes to `run_tests.sh`
- [x] Revert adding `uwshcu.F90.SER` which would be a separate PR for the serialization

2024-09-11 15:41 UTC, katrinafandrich commented
Merged with dsl/develop and resolved merge conflicts. Created UW directory and added README.md.

2024-09-11 16:31 UTC, katrinafandrich commented
Removed uwshcu.F90.SER

2025-05-02 18:49 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/field_types.py
> +from pyMoist.constants import N_MODES, NCNST
Like `N_MODES` this needs to be refactored in an `__init__` dependent system - which requires some thinking on out to do the `gtscript.Field` instantiation for data dimensions

2025-05-02 19:02 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +    while iteration < 10:
10?

2025-05-02 19:03 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +    while iteration < 10:
10?

2025-05-02 19:03 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +    D: Float,
Can we get something a little more descriptive here please

2025-05-02 19:04 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +        # cin = 1.0
Remove dead code?

2025-05-02 19:04 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +            # print("QSINVERT: derrdps=0 !!!")
Remove dead code

2025-05-02 19:04 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +        # print('Source air is too dry and pLCL is set to psmin in uwshcu.F90')
Warning from Fortran?

2025-05-02 19:05 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        k_inv = 71 - THIS_K
We need `71` to be an `__externals__`

2025-05-02 19:06 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +    For GEOS-specific questions, email nathan.arnold@nasa.gov
Add yourself here as "NDSL Port"

2025-05-02 19:08 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        if dotransport == 1.0:
`dotransport` is more like a `Bool`

2025-05-02 19:24 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        qt0: f32 = f32(qv0) + f32(ql0) + f32(qi0)
Why force the f32? Isn't this built in qv0,ql0 and qi0 ?

2025-05-02 19:25 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +            # wu[0, 0, 1] = 0.0
Dead code

2025-05-02 19:26 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                klcl = max(1, klcl)
Could that be `max(0, klcl-1)` ?

2025-05-02 19:27 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +            stop35 = False
We need to rename that with a comment to point to what it is in Fortran probably

2025-05-02 19:27 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                # thvubot = thvlsrc
?

2025-05-02 19:27 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                    #     """
You can remove `#`

2025-05-02 19:35 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        qisub_
This entire init block can't be there. We need an init step (allocate memory) then a zero'out step at runtime. Also do we need to `make_ijk_field` here? Why can't we just make quantities?

2025-05-02 19:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        qisub_
This should be a `for` loop and the iteration count should be a parameter of the class so it's set at init time

2025-05-02 19:37 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/README.md
Update if you can write down specifics of the NDSL port and/or an idea of where this UW comes from and what it does.

If not, remove

2025-05-02 20:05 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/README.md
Probably specify where we got the code, something like:

UW Shallow Water Convection physics port - from the Moist component.

This ports is aimed at the core numerics, e.g.: [uwshcu.F90](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/v2.5.2/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/uwshcu.F90)

Version ported: [v2.5.2](https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/v2.5.2) (as part of GEOS v11..5.2)

2025-05-06 15:56 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        if dotransport == 1.0:
Yeah dotransport behaves like a bool, I changed it from Float to Int

2025-05-08 14:09 UTC, twicki reviewed
intermediate review work

2025-05-08 18:20 UTC, katrinafandrich reviewed
First round PR comments done. Might still need some work for some of them. Moving onto Tobiases comments now.

2025-05-09 16:12 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        if id_check == 1:
I'm not sure, it behaves like a bool, but in the Fortran its an Int

2025-05-09 16:19 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/README.md
> +- Finish porting smaller functions/stencils in uwshcu
I updated the README.md so most of this is gone now

2025-05-09 16:21 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +    ncnst: Int,
Florian had this same comment. I changed it and now NCNST is now passed in as an external

2025-05-09 16:23 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +    iteration: i32,
I think because I define iteration in the init it has to be i32. Florian explained why but I don't remember. When I do "iteration: Int" it yells at me

2025-05-09 17:18 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                rho0inv = pifc0.at(K=kbelow) / (
No its not, so i cant do pifc0[0,0,-1] here

2025-05-09 17:39 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        ssthl0 = slope(
Are you sure we can do offsets in functions? I thought we couldn't, which is why I had to use this roundabout way to write the slope function

2025-05-12 18:28 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                    qtflx_out[0, 0, 1] = 0.0
Going to leave these as is for now based on our discussion from stand up the other day..

2025-05-12 18:28 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        qtflx_out[0, 0, 1] = 0.0
Going to leave these as is for now...

2025-05-13 15:15 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        ssthl0 = slope(
I split the slope function up into three functions: one for bottom layer, mid layers, and top layer

2025-05-13 16:49 UTC, katrinafandrich reviewed
First round of PR done. Should be ready to merge.

2025-05-14 15:36 UTC, FlorianDeconinck requested changes
Almost there, some cleanup.

As we said in the standup, the main thing for refactoring would be breaking up the `compute_uwschcu` code away, and potentially folding `temporaries` in the breakaway to have less of a huge block there. This can be log as a follow up refactor task

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/uwshcu_functions.py
> +P00 = f32(1e5)  # Reference pressure
Are those 32-bit per se, or `Float` ?

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +TAUFRZ = 450.0
```suggestion
TAUFRZ = Float(450.0)
```
?

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +NCNST = 23
Remove?

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/__init__.py
>  from .translate_qsat import TranslateQSat
Restore `TranslateGDFL_1M` in there

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/savepoint/translate_compute_uwshcu.py
> +# Merge netcdf files needed for testing UW
Remove comment

2025-05-14 15:36 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/tests/scripts/run_tests.sh
> +export PACE_TEST_N_THRESHOLD_SAMPLES=0
Duplicate.
Put back `FV3_DACEMODE=Python` for safety (this control orchestration)

2025-05-14 16:59 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                kinv = 5
If I read the code correctly, `kinv` is the inverse layer (K level). But if you have less than 5 level in your column, does it index out of bounds later?

2025-05-14 17:17 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/pyMoist_constants.py
> +TAUFRZ = 450.0
I don't think I ever touched these..weird but I will fix

2025-05-14 17:53 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +                kinv = 5
Okay I see now, probably should never happen but I will have it raise an error if it does

2025-05-14 18:27 UTC, katrinafandrich commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        # FloatFieldIJ NTracers
I'm confused, I thought I can't do this yet because NCNST needs to be a constant, but it also needs to be static at runtime so it can be used as a parameter to create the ntracer fields

2025-05-15 13:11 UTC, FlorianDeconinck commented on GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/pyMoist/pyMoist/UW/compute_uwshcu.py
> +        # FloatFieldIJ NTracers
So the `NCNST` should be known at `__init__` time.

The difference is that it shouldn't be known at `import` time which is what the system demands right now. I sometime use "runtime" a bit too broadly, my apologies. I expect that by `__init__` of UW we have read the configuration in and we know the size of the tracers

2025-05-16 13:41 UTC, katrinafandrich reviewed
More updates and ran pre-commit on all files. Should be ready to merge now.

2025-05-16 16:09 UTC, FlorianDeconinck approved these changes
LGTM - good job

2025-05-16 16:10 UTC, merged